import Tags from "../Tags";

export const ProjectsContent = [
  {
    purpose: {
      link: "https://letmeinubc.com",
      img: "personal.png",
      alt: "truffle",
      title: "Personal Project",
    },
    title: "LetMeIn UBC *2.0",
    description: [
      "After working with serverless infrastructure at Diligent, I realized we could use AWS to host our course tracking service for free. We stopped hosting our original LetMeIn UBC app because it was too costly for us to continually host without generating revenue.",
      "That's why this opportunity to build and deploy an impactful project that could help many UBC students, free of charge, was something I would not pass on.",
      "As <strong>lead architect and developer</strong>, I'm working with my friends to <strong>design and implement</strong> our app using AWS Lambda, Gateway, and other serverless infrastructure.",
    ],
    tools: [
      Tags.AwsCdk,
      Tags.React,
      Tags.TypeScript,
      Tags.Docker,
      Tags.BeautifulSoup,
    ],
    img: "letmein20.png",
    alt: "letmeinubc",
    github: "https://github.com/jlui17/LetMeInUBC-2.0",
    link: "https://letmeinubc.com",
  },
  {
    purpose: {
      link: "https://github.com/jlui17/",
      img: "personal.png",
      alt: "truffle",
      title: "Personal Project",
    },
    title: "Sorting Visualizer",
    description: [
      "Built this project over the weekend while completing a React course on Scrimba.",
      "This app helps people visualize and understajd different sorting algorithms",
    ],
    tools: [Tags.React],
    img: "sortingvisualizer.jpg",
    alt: "sortingvisualizer",
    github: "https://github.com/jlui17/SortingVisualizer",
    link: "https://jlui17sortingvisualizer.netlify.app/",
  },
  {
    purpose: {
      link: "https://github.com/jlui17/",
      img: "personal.png",
      alt: "truffle",
      title: "Personal Project",
    },
    title: "LetMeIn UBC",
    description: [
      "Inspired by July 13, 2021 (UBC course registration day) when some of my friends and I couldn't register for courses because they filled up. Instead of paying for a tracking service, we built our own.",
      "LetMeIn UBC helps students get into the courses they need by tracking the seat availability of course sections and notifying them when there is space.",
      "I implemented the front-end and API back-end.",
      "*Yes it does work.",
    ],
    tools: [Tags.Azure, Tags.Django, Tags.Twilio],
    img: "letmeinubc.png",
    alt: "letmeinubc",
    github: "https://github.com/kel-z/LetMeInUBC",
    link: "",
  },
  {
    purpose: {
      link: "https://github.com/jlui17/",
      img: "personal.png",
      alt: "truffle",
      title: "Personal Project",
    },
    title: "Algorithmic Trading Bot",
    description: [
      "On April 6, 2021, I attended an algorithmic trading workshop hosted by Scotiabank. In the Q&A, I asked about getting started and they recommended using Interactive Brokers TWS API. So, I teamed up with a friend and began my journey in algo trading.",
      "This application trades stocks using core algorithmic trading strategies (moving averages, momentum, growth) and the IB TWS API.",
      "I implemented the GUI, moving averages, and growth trading strategies.",
    ],
    tools: [Tags.IbTwsApi, Tags.Python, Tags.Pandas, Tags.PyQt],
    img: "tradingbot.png",
    alt: "algotrader",
    github: "https://github.com/jlui17/tws_api_trading_bot",
    link: "",
  },
  {
    purpose: {
      link: "https://globalgamejam.org/",
      img: "gamejam.png",
      alt: "globalgamejam",
      title: "Global Game Jam 2020",
    },
    title: "Echo",
    description: [
      "In January, my friend Alexa asked me to join her team for Global Game Jam 2020. I was a bit worried because I didn't have any game development experience, but I had a great time and the end product exceeded my expectations.",
      "Echo is a 2D side scroller RPG game concept developed in Unity. It's story is based around a child who has been separated from their mother in a forest and lost their vision. Follow them on their journey to reunite with their mother.",
      "I led the implementation of characters, scripting, game physics, and level design.",
    ],
    tools: [Tags.Unity],
    img: "echo.png",
    alt: "echo",
    github: "https://github.com/jlui17/Echo",
    link: "",
  },
  {
    purpose: {
      link: "https://github.com/jlui17/",
      img: "academic.png",
      alt: "ubc",
      title: "Academic Project (CPSC 304 - Relational Databases)",
    },
    title: "Carnival Operations DBMS",
    description: [
      "Based on the operations of a carnival games company.",
      "This application is a full stack project, with a React front-end, Flask back-end, and Oracle database. It allows users to interact with their operations database through a simple UI. Analysis is also provided using complex SQL queries to help the user evaluate their business performance.",
      "I led the system design and front-end development, helping design the tech stack, flow of information, and the implementation of each UI component.",
    ],
    tools: [Tags.React, Tags.Flask, Tags.TypeScript, Tags.Python, Tags.Oracle],
    img: "304.png",
    alt: "cs304",
    github:
      "https://github.students.cs.ubc.ca/CPSC304-2021W-T1/project_p7w2b_v9h3b_x8z2b",
    link: "",
  },
  {
    purpose: {
      link: "https://github.com/jlui17/",
      img: "academic.png",
      alt: "ubc",
      title: "Academic Project (CPSC 210 - Software Construction)",
    },
    title: "Inventory Manager",
    description: [
      "Based on the inventory management system at the Richmond Night Market.",
      "This application applies core OOP principles and the observable design pattern to emulate an inventory management system used in a carnival games operation.",
    ],
    tools: [Tags.Java, Tags.ObservableDesignPattern],
    img: "inventorymanager.png",
    alt: "inventory manager",
    github: "https://github.com/jlui17/W2F_Inv_Manager",
    link: "",
  },
  {
    purpose: {
      link: "https://github.com/jlui17/",
      img: "personal.png",
      alt: "truffle",
      title: "Personal Project",
    },
    title: "Sudoku Solver",
    description: [
      "At the start of 2020, despite almost no Python knowledge, the co-founders of GeekEdu hired me to teach K-12 students programming in Python. Not wanting to be a terrible instructor, I developed this project to learn the basics of Python.",
      "This application uses backtracking search to solve any sudoku puzzle.",
    ],
    tools: [Tags.PyGame, Tags.Python],
    img: "sudoku.png",
    alt: "sudoku",
    github: "https://github.com/jlui17/Sudoku-solver",
    link: "",
  },
];
