import Tags from "../Tags";

export const ExperiencesContent = [
  {
    position: "Software Development Engineer Intern",
    company: "Amazon (OPS)",
    link: "https://www.amazon.ca/",
    image: { file: "amazon.jpg", alt: "amazon" },
    duration: "May 2022 - Aug 2022",
    location: "Vancouver, BC, CAN",
    description: [
      "Building data services for the Fulfillment Execution team in the Supply Chain and Operations organization.",
    ],
    tools: [Tags.AwsCdk, Tags.Java],
  },
  {
    position: "Software Engineer",
    company: "Diligent",
    link: "https://www.diligent.com/",
    image: { file: "diligent.jpg", alt: "diligent" },
    duration: "Jan 2022 - May 2022",
    location: "Vancouver, BC, CAN",
    description: [
      "Improving business auditing and GRC through Diligent's HighBond platform.",
      "Applying serverless infrastructure on AWS using Terraform, leading meetings and E2E feature development, and developing and deploying production fixes for customer facing issue.",
    ],
    tools: [
      Tags.Aws,
      Tags.React,
      Tags.RubyOnRails,
      Tags.TypeScript,
      Tags.Terraform,
    ],
  },
  {
    position: "Assistant Manager",
    company: "Wun2Free Entertainment (Richmond Night Market)",
    link: "https://wun2free.com/",
    image: { file: "wun2free.png", alt: "wun2free" },
    duration: "Oct 2019 - Present",
    location: "Richmond, BC, CAN",
    description: [
      "I've been here since 2017. Although I could make more money elsewhere, working here is more about being part of the amazing culture and team. I truly enjoy working with everyone and it's something I can do alongside my main career on summer weekends.",
      "2022: Reduced HR costs by 99% ($2000 -> $15) by building a centralized, automated HR system using Google Workspace.",
      "2021: Opened and operated the games section on a shortened timeline and reduced capacity. Was involved in the planning and execution and setup and operations.",
      "2020: COVID-19 :(",
      "2019: Contributed to preseason inventory, planning, and setup processes. Oversaw nightly operations, ordered inventory, streamlined employee onboarding, and facilitated interviews.",
      "Through extra work and gumption, I also optimized inventory ordering by 50% (40 to < 20 hours) by implementing an automated excel database.",
    ],
    tools: [Tags.GoogleSheets, Tags.GoogleDrive, Tags.Excel],
  },
  {
    position: "Teaching Assistant (COMM 205: MIS)",
    company: "UBC Sauder School of Business",
    link: "https://www.sauder.ubc.ca/",
    image: { file: "sauder.png", alt: "ubcsauder" },
    duration: "Sep 2021 - Present",
    location: "Vancouver, BC, CAN",
    description: [
      "I took many of the excel skills I learned in the course and applied them to my job at Wun2Free to make a real impact. Seeing how practical and useful this course was inspired me to help others learn and apply the amazing skills this course has to offer.",
      "Currently supporting Professors Sabrina Rai, Zorana Svedic, Hasan Cavusoglu, and 120 students in UBC's largest business technology course.",
    ],
    tools: [Tags.Excel, Tags.R, Tags.Agile],
  },
  {
    position: "Programming Instructor",
    company: "GeekEducation",
    link: "https://www.geekedu.org/",
    image: { file: "geekedu.png", alt: "geekedu" },
    duration: "Jan 2021 - Aug 2021",
    location: "Vancouver, BC, CAN",
    description: [
      "I naively went into this job not expecting to learn much from tutoring. However, it ended up being one of the most impactful experiences of my early career and I'm super grateful to Michael and Matthew for believing in me.",
      "Who knew trying to explain complex programming concepts to K-12 students would help me build the skills that landed me my first internship?",
      "I helped K-12 students build fundamental programming skills in Python and Java.",
      "I also taught complex DSA computer science topics such as graphs, BFS/DFS, linked lists, recursion, fractals, and backtracking search to senior students.",
    ],
    tools: [Tags.Python, Tags.Java],
  },
  {
    position: "Supervisor",
    company: "Wun2Free Entertainment (Richmond Night Market)",
    link: "https://wun2free.com/",
    image: { file: "wun2free.png", alt: "wun2free" },
    duration: "May 2019 - Oct 2019",
    location: "Richmond, BC, CAN",
    description: [
      "Two years after selling games, I was given an opportunity to help lead the team I was part of. I took it and never looked back.",
      "I was responsible for supervising nightly operations to keep games up and running, planning social events, and mentoring games attendants. But I wanted to do more than that. I made new friends and helped make incremental improvements to business processes to build an amazing team and operation.",
      "Awarded the Partner of the Year Award for going beyond responsibilities to learn a management role and help realize seasonal success.",
    ],
    tools: [],
  },
  {
    position: "Games Attendant",
    company: "Wun2Free Entertainment (Richmond Night Market)",
    link: "https://wun2free.com/",
    image: { file: "wun2free.png", alt: "wun2free" },
    duration: "May 2017 - Oct 2018",
    location: "Richmond, BC, CAN",
    description: [
      "Initially, I was really bad at this job. I was shy, nervous, and quiet - not fit to sell carnival games. However, with the mentorship of my amazing managers, supervisors, and co-workers, I was able to come out of my shell and get good at yelling the same phrase over and over again.",
      "I talked to people, sold carnival games, gave away prizes, and had a great time.",
      "Awarded the Rising Star Award for distinguishing myself among games attendants in communication, customer service and leadership skills.",
    ],
    tools: [],
  },
];
