import Tags from "../Tags";

export const ExperiencesContent = [
  {
    position: "Teaching Assistant (CPSC 310: Software Engineering)",
    company: "The University of British Columbia",
    link: "https://www.ubc.ca/",
    image: { file: "ubc.svg", alt: "ubc" },
    duration: "Sep 2023 - Present",
    location: "Vancouver, BC, CAN",
    description: [
      "Hosting labs and office hours. Helping students beep and boop.",
    ],
    tools: [Tags.TypeScript],
  },
  {
    position: "Software Development Engineer Intern",
    company: "Amazon (OPS)",
    link: "https://www.amazon.ca/",
    image: { file: "amazon.jpg", alt: "amazon" },
    duration: "May 2023 - Sep 2023",
    location: "Vancouver, BC, CAN",
    description: [
      "Returned to SCOT and built a data pipeline and visualization tool on the worlds largest supply chain.",
    ],
    tools: [Tags.Aws, Tags.Java],
  },
  {
    position: "Assistant Manager",
    company: "Wun2Free Entertainment (Richmond Night Market)",
    link: "https://wun2free.com/",
    image: { file: "wun2free.png", alt: "wun2free" },
    duration: "Oct 2019 - Sep 2023",
    location: "Richmond, BC, CAN",
    description: [
      "I beep boop to minimize the amount of work my team does by automating everything with Google Sheets.",
      "2023: Scaling our HR system by beep booping. React and TypeScript for the frontend. AWS Lambda, API Gateway, Golang and Google Sheets API for the backend.",
      "2022: Reduced HR costs by 99% ($2000 -> $15) by building a centralized and automated on-boarding, scheduling, record-keeping, and payroll all-in-one system using Google Sheets.",
      "2021: Optimized inventory ordering by 50% (40 -> 20 hours) by implementing an automated Excel database.",
      "2019-2020: Learning the ropes.",
    ],
    tools: [
      Tags.Aws,
      Tags.Go,
      Tags.React,
      Tags.TypeScript,
      Tags.GoogleSheets,
      Tags.GoogleDrive,
      Tags.Excel,
    ],
  },
  {
    position: "Software Development Engineer Intern",
    company: "Amazon (OPS)",
    link: "https://www.amazon.ca/",
    image: { file: "amazon.jpg", alt: "amazon" },
    duration: "May 2022 - Aug 2022",
    location: "Vancouver, BC, CAN",
    description: [
      "Supply Chain Optimization Technology (SCOT)",
      "I beeped and booped to build 2 micro-services for a long-term storage big data pipeline using AWS Kinesis, Java, and AWS CDK with TypeScript.",
    ],
    tools: [Tags.AwsCdk, Tags.Java],
  },
  {
    position: "Software Engineer",
    company: "Diligent",
    link: "https://www.diligent.com/",
    image: { file: "diligent.jpg", alt: "diligent" },
    duration: "Jan 2022 - May 2022",
    location: "Vancouver, BC, CAN",
    description: [
      "Core Projects Team",
      "This was my first time learning how to beep boop in a team of beep boopers.",
      "I delivered full-stack features, deployed serverless infrastructure on AWS using Terraform, and fixes for customer facing issue in Ruby on Rails, React, and TypeScript.",
    ],
    tools: [
      Tags.Aws,
      Tags.React,
      Tags.RubyOnRails,
      Tags.TypeScript,
      Tags.Terraform,
    ],
  },
  {
    position: "Teaching Assistant (COMM 205: MIS)",
    company: "UBC Sauder School of Business",
    link: "https://www.sauder.ubc.ca/",
    image: { file: "sauder.png", alt: "ubcsauder" },
    duration: "Sep 2021 - Present",
    location: "Vancouver, BC, CAN",
    description: [
      "Supporting professors Adam Saunders, Sabrina Rai, Zorana Svedic, Hasan Cavusoglu, and 120 students in UBC’s largest business technology course. A bit of beep booping.",
    ],
    tools: [Tags.Excel, Tags.R, Tags.Agile],
  },
  {
    position: "Programming Instructor",
    company: "GeekEducation",
    link: "https://www.geekedu.org/",
    image: { file: "geekedu.png", alt: "geekedu" },
    duration: "Jan 2021 - Aug 2021",
    location: "Vancouver, BC, CAN",
    description: [
      "I helped K-12 students learn how to beep boop in Python and Java.",
      "I taught complex DSA concepts such as graphs, BFS, DDS, linked lists, recursion, fractals, and backtracking search to senior students.",
    ],
    tools: [Tags.Python, Tags.Java],
  },
  {
    position: "Supervisor",
    company: "Wun2Free Entertainment (Richmond Night Market)",
    link: "https://wun2free.com/",
    image: { file: "wun2free.png", alt: "wun2free" },
    duration: "May 2019 - Oct 2019",
    location: "Richmond, BC, CAN",
    description: [
      "Two years after selling games, I was given an opportunity to help lead the team I was part of. I took it and never looked back.",
      "I was responsible for supervising nightly operations to keep games up and running, planning social events, and mentoring games attendants. But I wanted to do more than that. I made new friends and helped make incremental improvements to business processes to build an amazing team and operation.",
      "Awarded the Partner of the Year Award for going beyond responsibilities to learn a management role and help realize seasonal success.",
    ],
    tools: [],
  },
  {
    position: "Games Attendant",
    company: "Wun2Free Entertainment (Richmond Night Market)",
    link: "https://wun2free.com/",
    image: { file: "wun2free.png", alt: "wun2free" },
    duration: "May 2017 - Oct 2018",
    location: "Richmond, BC, CAN",
    description: [
      "Initially, I was really bad at this job. I was shy, nervous, and quiet - not fit to sell carnival games. However, with the mentorship of my amazing managers, supervisors, and co-workers, I was able to come out of my shell and get good at yelling the same phrase over and over again.",
      "I talked to people, sold carnival games, gave away prizes, and had a great time.",
      "Awarded the Rising Star Award for distinguishing myself among games attendants in communication, customer service and leadership skills.",
    ],
    tools: [],
  },
];
