// Map props in the sprite format: rows of characters, one per pixel, through one
// shared palette. Drawn on the sprites' grid (1 CSS px per pixel, Justin is 62px
// tall) with the sprites' outline rule: ink #1e1711, a closed 2px outer outline,
// 1px interior lines and small features. Every prop is pinned by its bottom-left
// corner on the ground line it stands on. The rows were laid out with small pixel
// helpers (fill, ellipse, an outline pass) and then checked at 6x; edit the rows
// here if a pixel is wrong.

export const palette = {
  ".": null,
  x: null, // transparent, but part of the silhouette for the outline pass (the net's mesh panel)
  k: "#1e1711", // ink, the sprites' ink
  W: "#8b6a4d", // wood
  w: "#a88562", // wood, lit edge
  M: "#efe3cf", // linen, plaster, net tape, snow, pages
  L: "#e2d4bb", // linen in shade: the sheet, the awning's pale stripe
  Q: "#7b93b3", // blanket
  q: "#9fb1c9", // blanket fold
  R: "#a8674a", // rust roof, the cookbook's cover
  A: "#d1913f", // awning stripe, lampshade (luibuilder's orange)
  G: "#c5d4de", // glass
  B: "#a9c1d4", // lit screen
  S: "#c9c2b8", // brushed steel
  s: "#a39b91", // steel shade, net mesh, handwriting
  o: "#4a2e1e", // espresso, the grinder's body
  b: "#5e7fa3", // volleyball panel (luibot's blue)
  y: "#d9b25a", // volleyball panel, straw
  T: "#8a9a5b", // canopy
  t: "#a3b26e", // canopy, lit side
  m: "#8d9bb0", // mountain
  d: "#74839a", // mountain, shaded face
};

// Bed, 100x52: headboard on the left, pillow, a blue blanket, low footboard. The mattress top is row 28; a sleeping sprite's bottom row sits on row 27.
export const bed = [
  "..kkkkkkkkkkkk......................................................................................",
  ".kkkkkkkkkkkkkk.....................................................................................",
  "kkkwwwwwwwwwwkkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk....................................................................................",
  "kkwwWWWWWWWWWWkk......................................................................kkkkkkkkkkkk..",
  "kkwwWWWWWWWWWWkk.....................................................................kkkkkkkkkkkkkk.",
  "kkwwWWWWWWWWWWkkkkkkkkkkkkkkkkkkk...................................................kkkwwwwwwwwwwkkk",
  "kkwwWWWWWWWWWWkkkkkkkkkkkkkkkkkkkk..................................................kkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkkMMMMMMMMMMMMMMMMkkk.................................................kkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkMMMMMMMMMMMMMMMMMMkk.................................................kkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkMMMMMMMMMMMMMMMMMMkk.................................................kkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkMMMMMMMMMMMMMMMMMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkMMMMMMMMMMMMMMMMMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkMMMMMMMMMMMMMMMMMMkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLkMMMMMMMMMMMMMMMMkLkQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLkkkkkkkkkkkkkkkkkkLkQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLLLLLLLLLLLLLLLLLLLLkQQQQQqqqqqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQqqqqqQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLLLLLLLLLLLLLLLLLLLLkQQQQQQQQQQQQQQQQQQQQQQQqqqqqqqqQQQQQQQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLLLLLLLLLLLLLLLLLLLLkQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLLLLLLLLLLLLLLLLLLLLkQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLLLLLLLLLLLLLLLLLLLLkQQQQQQQQQQQqqqqqqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLLLLLLLLLLLLLLLLLLLLkQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQqqqqqqQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLLLLLLLLLLLLLLLLLLLLkQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWLLLLLLLLLLLLLLLLLLLLkQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkk....................................................................kkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkk....................................................................kkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkk....................................................................kkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkk....................................................................kkwwWWWWWWWWWWkk",
  "kkwwWWWWWWWWWWkk....................................................................kkwwWWWWWWWWWWkk",
  "kkkkkkkkkkkkkkkk....................................................................kkkkkkkkkkkkkkkk",
  ".kkkkkkkkkkkkkk......................................................................kkkkkkkkkkkkkk.",
];

// Cafe, 108x128: rust roof, plaster wall, a striped awning over a window with an espresso machine in it, a wooden door (68px, he fits) with a small window above.
export const cafe = [
  "............................................................................................................",
  "............................................................................................................",
  "............................................................................................................",
  "............................................................................................................",
  "............................................................................................................",
  "............................................................................................................",
  ".......................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......................",
  "......................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......................",
  ".....................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....................",
  "....................kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk....................",
  "...................kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk...................",
  "..................kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk..................",
  ".................kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk.................",
  "................kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk................",
  "...............kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk...............",
  "..............kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk..............",
  ".............kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk.............",
  "............kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk............",
  "...........kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk...........",
  "..........kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk..........",
  ".........kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk.........",
  "........kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk........",
  ".......kkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkk.......",
  ".....kkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkk.....",
  "....kkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkk....",
  "....kkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkk....",
  "....kkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkk....",
  "....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....",
  "....kkkkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkkk....",
  ".....kkkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk.....",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkkkkkkkkkkkkkkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLAAAALLLLkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMkAAMMMLLMAAMMMLLMAAMMMLLMAAMMMLLMAAMMMLLMAAMMMLLMkMMMMMMMMMMMMkGGGGGGGGGGGGkMMMMMMMMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkkkkkkkkkkkkkMMMMMMMMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMMMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkwwwwwwwwwwwwwwwwwwwwwwwwkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGMMMMMMMMMMMMMMMMMMMMMMMMGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGMMMMMMMMMMMMMMMMMMMMMMMMGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkkkkkkkkkkkkkkkkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSkkkkkkkkSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSkkkkkkkkSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSkkkkkkkkSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSkkSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSkkSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkGGGGGGGGGGGGGGkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSGGGGGGGGGGGGGkMMMMMMkkwwWWkkkkkkkkkkkkkkkkWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGssssssssssssssssssssssssGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGssssssssssssssssssssssssGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGssssssssssssssssssssssssGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGssssssssssssssssssssssssGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGooooooGGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGMMMMMMkGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGMMMMMMkGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGGGGGGGGGGMMMMMMGGGGGGGGGGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGkkkkkkkkkkkkkkkkkkkkkkkkGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkGGGGGGGkkkkkkkkkkkkkkkkkkkkkkkkGGGGGGGGGGGGGkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMksssssssssssssssssssssssssssssssssssssssssssskMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWkkkkkkkkkkkkkkkkkkWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWkkkWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWkkkWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWkkkWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkwwWWWWWWWWWWWWWWWWWWWWWWkkMMMMMMkk......",
  "......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......",
  ".......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......",
  "............................................................................................................",
  "............................................................................................................",
];

export const cafeGlass = [[15,51,44,34],[73,63,14,10],[74,37,12,10]]; // the panes, [x, y, w, h] in prop pixels: lit at night

// Volleyball net, 100x92: two steel posts, a taped mesh panel; the top tape is at 2.4 of his height, like a real net.
export const net = [
  ".kkkkkk......................................................................................kkkkkk.",
  "kkkkkkkk....................................................................................kkkkkkkk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSskk",
  "kkSSSskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSskk",
  "kkSSSskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSskk",
  "kkSSSsMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSskk",
  "kkSSSsMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSskk",
  "kkSSSsMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSskk",
  "kkSSSskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSssxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSssxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSssxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSssxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSssxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSssxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSssxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSssxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxsxxxSSSskk",
  "kkSSSsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsxsSSSskk",
  "kkSSSsMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSskk",
  "kkSSSsMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSskk",
  "kkSSSskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSskk",
  "kkSSSskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkSSSskk....................................................................................kkSSSskk",
  "kkkkkkkk....................................................................................kkkkkkkk",
  ".kkkkkk......................................................................................kkkkkk.",
];

// Low table, 108x60: chest height for someone sitting on the ground. A pot with its lid on, a cup, and the cookbook open.
export const table = [
  "............................................................................................................",
  "............................................................................................................",
  "............................................................................................................",
  "............................................................................................................",
  "............................................................................................................",
  "............................................................................................................",
  ".....................................................kkkkkk.................................................",
  "....................................................kkkkkkkk................................................",
  "....................................................kkkkkkkk................................................",
  ".........................................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....................................",
  "........................................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................................",
  "........................................kkSSSSSSSSSSSSSSSSSSSSSSSSSSSSkk....................................",
  "........................................kkSSSSSSSSSSSSSSSSSSSSSSSSSSSSkk....................................",
  "........................................kkSSSSSSSSSSSSSSSSSSSSSSSSSSSSkk....................................",
  "........................................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................................",
  ".........................................kkkSSMSSSSSSSSSSSSSSSSSSSSSkkk.....................................",
  ".......................................kkkkkSSMSSSSSSSSSSSSSSSSSSSSSkkkkk...................................",
  "......................................kkkkkkSSMSSSSSSSSSSSSSSSSSSSSSkkkkkk..................................",
  "......................................kkkkkkSSMSSSSSSSSSSSSSSSSSSSSSkkkkkk..................................",
  "......................................kkkkkkSSMSSSSSSSSSSSSSSSSSSSSSkkkkkk............kkk...................",
  ".......................kkkkkkkkkkkk...kkkkkkSSMSSSSSSSSSSSSSSSSSSSSSkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......",
  "......................kkkkkkkkkkkkkk..kkkkkkSSMSSSSSSSSSSSSSSSSSSSSSkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......",
  "......................kkooooooooookkk..kkkkkSSMSSSSSSSSSSSSSSSSSSSSSkkkkkkMMMMMMMMMMMMMkMMMMMMMMMMMMkk......",
  "......................kkMMMMMMMMMMkkkk....kkSSMSSSSSSSSSSSSSSSSSSSSSkk..kkMMMMMMMMMMMMMkMMMMMMMMMMMMkk......",
  "......................kkMMMMMMMMMMkkkk....kkSSMSSSSSSSSSSSSSSSSSSSSSkk..kkMMMsssssssMMMkMMsssssssMMMkk......",
  "......................kkMMMMMMMMMMkkkk....kkSSMSSSSSSSSSSSSSSSSSSSSSkk..kkMMMMMMMMMMMMMkMMMMMMMMMMMMkk......",
  "......................kkMMMMMMMMMMkkkk....kkssMssssssssssssssssssssskk.kkkMMMMssssssMMMkMMMsssssMMMMkkk.....",
  "......................kkMMMMMMMMMMkkkk....kksssssssssssssssssssssssskk.kkRMMMMMMMMMMMMMkMMMMMMMMMMMMRkk.....",
  ".kkkkkkkkkkkkkkkkkkkkkkkMMMMMMMMMMkkkkkkkkkksssssssssssssssssssssssskkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkkk.",
  "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
  "kkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkk",
  "kkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkk",
  "kkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkk",
  "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
  "kkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkk",
  "kkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkk",
  "kkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkk",
  "kkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkk",
  "kkkkkkkkwWWWWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwWWWWWWWkkkkkkkk",
  ".kkkkkkkwWWWWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwWWWWWWWkkkkkkk.",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................kkwWWWWWWWkk......",
  "......kkkkkkkkkkkk........................................................................kkkkkkkkkkkk......",
  ".......kkkkkkkkkk..........................................................................kkkkkkkkkk.......",
];

// Desk, 140x88: a monitor with a few lines on screen, the Bambino Plus, the Encore grinder, and a lamp at the right end.
export const desk = [
  "............................................................................................................................................",
  "............................................................................................................................................",
  "............................................................................................................................................",
  "............................................................................................................................................",
  "............................................................................................................................................",
  "............................................................................................................................................",
  "...........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...................................................................................",
  "..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..................................................................................",
  "..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...........................................................kkkkkkkk...............",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..........................................................kkkkkkkkkk..............",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk.........................................................kkkAAAAAAkkk.............",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk........................................................kkkAAAAAAAAkkk............",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk.......................................................kkkAAAAAAAAAAkkk...........",
  "..........kkkBBBBkkkkkkkkkkkkkkBBBBBBBBBBBBBBBBBBBBBBBBkkk......................................................kkkAAAAAAAAAAAAkkk..........",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk.....................................................kkkAAAAAAAAAAAAAAkkk.........",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk....................................................kkkAAAAAAAAAAAAAAAAkkk........",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk.................................kkkkkkkkkkkk......kkkAAAAAAAAAAAAAAAAAAkkk.......",
  "..........kkkBBBBkkkkkkkkkkkkkkkkkkkkkkBBBBBBBBBBBBBBBBkkk................................kkkkkkkkkkkkkk.....kkkkkkkkkkkkkkkkkkkkkkkk.......",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk................................kkkkkkkkkkkkkk.....kkkkkkkkkkksskkkkkkkkkkk.......",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk................................kkGGGGGGGGGGkk......kkkkkkkkkksskkkkkkkkkk........",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk................................kkGGGGGGGGGGkk..............kksskk................",
  "..........kkkBBBBkkkkkkkkkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk................................kkGGGGGGGGGGkk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk...kkkkkkkkkkkkkkkkkkkkkkkk.....kkGGGGGGGGGGkk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkkkkkkkkkkkkkkkkkkkkkkkkk....kkGGGGGGGGGGkk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkMMMMMMMMMMMMMMMMMMMMMMkk...kkkGGGGGGGGGGkkk.............kksskk................",
  "..........kkkBBBBkkkkkkkkkkkkkkkkkkkkkkkkkkBBBBBBBBBBBBkkk..kkSSSSSSSSSSSSSSSSSSSSSSkk...kkooooooooooookk.............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSSSSSSSSSSSSSSSSkk...kkooooooooooookk.............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSSSSSSSSSSSSSSSSkk...kkooooooooooookk.............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSSSSSSSSSSSSSSSSkk...kkkosooooooookkk.............kksskk................",
  "..........kkkBBBBkkkkkkkkkkkkkkkkkkBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSSSSSSSSSSSSSSSSkk....kkosooooooookk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSSSSSSSSSSSSSSSSkk....kkosooooooookk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSkkkkkkkkSSSSSSSkk....kkosooooooookk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSkkkkkkkkSSSSSSSkk....kkosooooooookk..............kksskk................",
  "..........kkkBBBBkkkkkkkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSkkkkkkkkSSSSSSSkk....kkosooooooookk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSSSSkkSSSSSSSSSSkk....kkosooooooookk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSSSSkkSSSSSSSSSSkk....kkosooooooookk..............kksskk................",
  "..........kkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkk..kkSSSSSSSSSSkkSSSSSSSSSSkk....kkosssssssookk..............kksskk................",
  "..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..kkSSSSSSSSSSSSSSSSSSSSSSkk....kkosssssssookk..............kksskk................",
  "..........kkkkkkkkkkkkkkkkkkkkksssssskkkkkkkkkkkkkkkkkkkkk..kksssssssssssssssssssssskk....kkoossssssookk..............kksskk................",
  "...........kkkkkkkkkkkkkkkkkkkksssssskkkkkkkkkkkkkkkkkkkk...kksssssssssssssssssssssskk....kkoossssssookk.........kkkkkkksskkkkkkk...........",
  "........................kkkkkkksssssskkkkkkk................kkssssssssoooooosssssssskk....kkoossssssookk........kkkkkkkksskkkkkkkk..........",
  "........................kkSSSSSSSSSSSSSSSSkk................kkssssssssMMMMMMsssssssskk....kkoossssssookk........kkSSSSSSSSSSSSSSkk..........",
  ".kkkkkkkkkkkkkkkkkkkkkkkkksssssssssssssssskkkkkkkkkkkkkkkkkkkkssssssssMMMMMMsssssssskkkkkkkkoossssssookkkkkkkkkkkksssssssssssssskkkkkkkkkkk.",
  "kkkkkkkkkkkkkkkkkkkkkkkkkksssssssssssssssskkkkkkkkkkkkkkkkkkkksssssssssssssssssssssskkkkkkkkoossssssookkkkkkkkkkkksssssssssssssskkkkkkkkkkkk",
  "kkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkk",
  "kkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkk",
  "kkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkk",
  "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
  "kkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkk",
  "kkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkk",
  "kkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkk",
  "kkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkk",
  "kkkkkkkkwWWWWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwWWWWWWWkkkkkkkk",
  ".kkkkkkkwWWWWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwWWWWWWWkkkkkkk.",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkwWWWWWWWkk........................................................................................................kkwWWWWWWWkk......",
  "......kkkkkkkkkkkk........................................................................................................kkkkkkkkkkkk......",
  ".......kkkkkkkkkk..........................................................................................................kkkkkkkkkk.......",
];

export const deskLamp = [111,8,20,10]; // the lamp's glow at night, [x, y, w, h] in prop pixels

// A big lumpy tree, 50x82.
export const bigTree = [
  "..................................................",
  "..................................................",
  "...................kkkkkkkkkkk....................",
  "...............kkkkkkkkkkkkkkkkkkk................",
  ".............kkkkkkkTTTTTTTTTkkkkkkk..............",
  "...........kkkkkTTTTTTTTTTTTTTTTTkkkkk............",
  ".........kkkkkTTTTTTTTTTTTTTTTTTTTTkkkkk..........",
  "........kkkkTTTTTTTTTTTTTTtttttTTTTTTkkkk.........",
  ".......kkkTTTTTTTTTTTTTTtttttttttTTTTTTkkk........",
  "......kkkTTTTTTTTTTTTTTtttttttttttTTTTTTkkk.......",
  ".....kkkTTTTtttttttTTTTtttttttttttTTTTTTTkkk......",
  "....kkkTTTtttttttttttTTtttttttttttTTTTTTTTkkk.....",
  "....kkTTtttttttttttttttTtttttttttTTTTTTTTTTkk.....",
  "...kkkTTtttttttttttttttTTTtttttTTTTTTTTTTTTkkk....",
  "...kkTTtttttttttttttttttTTTTTTTTTTTTTTTTTTTTkk....",
  "..kkkTTtttttttttttttttttTTTTTTTTTTTTTTTTTTTTkkk...",
  "..kkTTTtttttttttttttttttTTTTTTTTTTTTTTTTTTTTTkk...",
  "..kkTTTTtttttttttttttttTTTTTTTTTTTTTTTTTTTTTTkk...",
  ".kkkTTTTtttttttttttttttTTTTTTTTTTTTTTTTTTTTTTkkk..",
  ".kkTTTTTTTtttttttttttTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTtttttttTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk..",
  ".kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk.",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk.",
  "kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk",
  "kkTTTTTTTttttTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk",
  "kkTTTTTTTttttTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk",
  "kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk",
  "kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk",
  "kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk",
  "kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk.",
  ".kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk.",
  "..kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk..",
  "...kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk...",
  "....kkkTTTTTTTTTTTTTTTTTTTTTTkTTTTTTTTTTTTTkkk....",
  ".....kkkkkTTTTTTTkkkkkkkkkkkkkkkkTTTTTTTkkkkk.....",
  "......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......",
  ".........kkkkkkkkkkkwwWWWWWWkk..kkkkkkkkk.........",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "..................kkwwWWWWWWkk....................",
  "................kkkkwwWWWWWWkkkk..................",
  "...............kkkkkwwWWWWWWkkkkk.................",
  "...............kkwwWWWWWWWWWWWWkk.................",
  "...............kkwwWWWWWWWWWWWWkk.................",
  "...............kkwwWWWWWWWWWWWWkk.................",
  "...............kkwwWWWWWWWWWWWWkk.................",
  "...............kkkkkkkkkkkkkkkkkk.................",
  "................kkkkkkkkkkkkkkkk..................",
  "..................................................",
];

// A rounder, narrower tree, 40x74.
export const roundTree = [
  "............kkkkkkkkkkkkkkk.............",
  "..........kkkkkkTTTTTTTkkkkkk...........",
  ".........kkkkTTTTTTTTTTTTTkkkk..........",
  "........kkkTTTTTTTTTTTTTTTTTkkk.........",
  ".......kkkTTTTTTTTTTTTTTTTTTTkkk........",
  "......kkkTTTTTTTTTTTTTTTTTTTTTkkk.......",
  ".....kkkTTTTTTTTTTTTTTTTTTTTTTTkkk......",
  "....kkkTTTtttttttTTTTTTTTTTTTTTTkkk.....",
  "....kkTTtttttttttttTTTTTTTTTTTTTTkk.....",
  "...kkkTtttttttttttttTTTTTTTTTTTTTkkk....",
  "...kkTTtttttttttttttTTTTTTTTTTTTTTkk....",
  "..kkkTtttttttttttttttTTTTTTTTTTTTTkkk...",
  "..kkTTtttttttttttttttTTTTTTTTTTTTTTkk...",
  "..kkTTtttttttttttttttTTTTTTTTTTTTTTkk...",
  "..kkTTTtttttttttttttTTTTTTTTTTTTTTTkk...",
  ".kkkTTTtttttttttttttTTTTTTTTTTTTTTTkkk..",
  ".kkTTTTTtttttttttttTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTtttttttTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTtttTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTtttTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk..",
  "..kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk...",
  "..kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk...",
  "..kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk...",
  "..kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk...",
  "...kkTTTTTTTTTTTTTTTTTTTTTTTTTTTTTkk....",
  "...kkkTTTTTTTTTTTTTTTTTTTTTTTTTTTkkk....",
  "....kkTTTTTTTTTTTTTTTTTTTTTTTTTTTkk.....",
  "....kkkTTTTTTTTTTTTTTTTTTTTTTTTTkkk.....",
  ".....kkkTTTTTTTTTTTTTTTTTTTTTTTkkk......",
  "......kkkTTTTTTTTTTTTTTTTTTTTTkkk.......",
  ".......kkkTTTTTTTTTTTTTTTTTTTkkk........",
  "........kkkTTTTTTTTTTTTTTTTTkkk.........",
  ".........kkkkTTTTTTTTTTTTTkkkk..........",
  "..........kkkkkkTTTTTTTkkkkkk...........",
  "............kkkkkkkkkkkkkkk.............",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  "..............kkwwWWWWkk................",
  ".............kkkwwWWWWkkk...............",
  "............kkkkwwWWWWkkkk..............",
  "............kkWWWWWWWWWWkk..............",
  "............kkWWWWWWWWWWkk..............",
  "............kkWWWWWWWWWWkk..............",
  "............kkkkkkkkkkkkkk..............",
  ".............kkkkkkkkkkkk...............",
  "........................................",
];

// A bush, 30x20.
export const bush = [
  "..............................",
  "..............................",
  "..............................",
  ".......kkkkkkkkkkkkk..........",
  ".....kkkkkkkkkkkkkkkkkk.......",
  "....kkkktttttTTTTTTkkkkkk.....",
  "...kkktttttttttTTTTTTTkkkk....",
  "..kkkTtttttttttTTTTTTTTTkkk...",
  "..kkTTtttttttttTTTTTTTTTTkk...",
  ".kkkTTTTtttttTTTTTtttTTTTkkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkTTTTTTTTTTTTTTTTTTTTTTTkk..",
  ".kkkTTTTTTTTTTTTTTTTTTTTTkkk..",
  "..kkTTTTTTTTTTTTTTTTTTTTTkk...",
  "..kkkTTTTTTTTTTTTTTTTTTTkkk...",
  "...kkkkTTTTTTTTTTTTTTTkkkk....",
  "....kkkkkkTTTTTTTTTkkkkkk.....",
  "......kkkkkkkkkkkkkkkkk.......",
  ".........kkkkkkkkkkk..........",
];

// Signpost, 88x72: two long planks pointing right; the page letters them (Vancouver above NYC).
export const signpost = [
  "........................................................................................",
  "........................................................................................",
  "........................................................................................",
  "........................................................................................",
  "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....................",
  "..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk...................",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk..................",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk.................",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk................",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk...............",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk...............",
  "..kkMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMkk...............",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk...............",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk................",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk.................",
  "..kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk..................",
  "..kkMMMMMMMMMMkkkkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk...................",
  "..kkkkkkkkkkwwWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....................",
  "...kkkkkkkkkwwWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....................",
  ".......kkkkkwwWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...............................",
  "......kkkkkkwwWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..............................",
  "......kkMMMMMMkkkkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk.............................",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk............................",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk...........................",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk..........................",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk..........................",
  "......kkMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMkk..........................",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk..........................",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk...........................",
  "......kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk............................",
  "......kkMMMMMMkkkkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkkk.............................",
  "......kkkkkkwwWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..............................",
  ".......kkkkkwwWWWWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...............................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkwwWWWWkk....................................................................",
  "..........kkkkkkkkkk....................................................................",
  "...........kkkkkkkk.....................................................................",
];

export const signpostWords = [[10,8],[14,24]]; // [left, top] of each plank's face, in prop pixels

// luibuilder's blocks, 30x24: two cream blocks and a third on top.
export const crates = [
  ".......kkkkkkkkkkkkkk.........",
  "......kkkkkkkkkkkkkkkk........",
  "......kkLLLLLLLLLLLLkk........",
  "......kkkkkkkkkkkkkkkk........",
  "......kkMMMMMMMMMMMMkk........",
  "......kkMMMMMMMMMMMMkk........",
  "......kkMMMMMMMMMMMMkk........",
  "......kkMMMMMMMMMMMMkk........",
  "......kkMMMMMMMMMMMMkk........",
  "......kkMMMMMMMMMMMMkk........",
  ".kkkkkkkMMMMMMMMMMMMkkkkkkkk..",
  "kkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  "kkLLLLLLkkkkkkkkkkkkLLLLLLLkk.",
  "kkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  "kkMMMMMMMMMMMMkMMMMMMMMMMMMkk.",
  "kkMMMMMMMMMMMMkMMMMMMMMMMMMkk.",
  "kkMMMMMMMMMMMMkMMMMMMMMMMMMkk.",
  "kkMMMMMMMMMMMMkMMMMMMMMMMMMkk.",
  "kkMMMMMMMMMMMMkMMMMMMMMMMMMkk.",
  "kkMMMMMMMMMMMMkMMMMMMMMMMMMkk.",
  "kkMMMMMMMMMMMMkMMMMMMMMMMMMkk.",
  "kkMkkkkkkkkkkMkMMMMMMMMMMMMkk.",
  "kkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  ".kkkkkkkkkkkkkkkkkkkkkkkkkkk..",
];

// Volleyball, 18px: cream with a blue and a yellow panel (his axis). Four frames, a quarter turn clockwise each, for the roll.
export const volleyball = [
  [
    ".....kkkkkkkk.....",
    "....kkkkkkkkkk....",
    "...kkkMMMMMbkkk...",
    "..kkkMMMMMMbbkkk..",
    ".kkkMMMMMMbbbbkkk.",
    "kkkMMMMMMMbbbbbkkk",
    "kkMMMMMMMMbbbbbbkk",
    "kkyMMMMMMbbbbbbbkk",
    "kkyyyyyMMbbbbbbbkk",
    "kkyyyyyyyMMbbbbbkk",
    "kkyyyyyyyMMMMMbbkk",
    "kkyyyyyyMMMMMMMMkk",
    "kkkyyyyyMMMMMMMkkk",
    ".kkkyyyyMMMMMMkkk.",
    "..kkkyyyMMMMMkkk..",
    "...kkkyMMMMMkkk...",
    "....kkkkkkkkkk....",
    ".....kkkkkkkk.....",
  ],
  [
    ".....kkkkkkkk.....",
    "....kkkkkkkkkk....",
    "...kkkyyyyyMkkk...",
    "..kkkyyyyyMMMkkk..",
    ".kkkyyyyyyMMMMkkk.",
    "kkkyyyyyyyMMMMMkkk",
    "kkyyyyyyyyMMMMMMkk",
    "kkMyyyyyyMMMMMMMkk",
    "kkMMMMMyyMMMMMMMkk",
    "kkMMMMMMMbbMMMMMkk",
    "kkMMMMMMMbbbbbMMkk",
    "kkMMMMMMbbbbbbbbkk",
    "kkkMMMMMbbbbbbbkkk",
    ".kkkMMMMbbbbbbkkk.",
    "..kkkMMbbbbbbkkk..",
    "...kkkMbbbbbkkk...",
    "....kkkkkkkkkk....",
    ".....kkkkkkkk.....",
  ],
  [
    ".....kkkkkkkk.....",
    "....kkkkkkkkkk....",
    "...kkkMMMMMykkk...",
    "..kkkMMMMMyyykkk..",
    ".kkkMMMMMMyyyykkk.",
    "kkkMMMMMMMyyyyykkk",
    "kkMMMMMMMMyyyyyykk",
    "kkbbMMMMMyyyyyyykk",
    "kkbbbbbMMyyyyyyykk",
    "kkbbbbbbbMMyyyyykk",
    "kkbbbbbbbMMMMMMykk",
    "kkbbbbbbMMMMMMMMkk",
    "kkkbbbbbMMMMMMMkkk",
    ".kkkbbbbMMMMMMkkk.",
    "..kkkbbMMMMMMkkk..",
    "...kkkbMMMMMkkk...",
    "....kkkkkkkkkk....",
    ".....kkkkkkkk.....",
  ],
  [
    ".....kkkkkkkk.....",
    "....kkkkkkkkkk....",
    "...kkkbbbbbMkkk...",
    "..kkkbbbbbbMMkkk..",
    ".kkkbbbbbbMMMMkkk.",
    "kkkbbbbbbbMMMMMkkk",
    "kkbbbbbbbbMMMMMMkk",
    "kkMMbbbbbMMMMMMMkk",
    "kkMMMMMbbMMMMMMMkk",
    "kkMMMMMMMyyMMMMMkk",
    "kkMMMMMMMyyyyyyMkk",
    "kkMMMMMMyyyyyyyykk",
    "kkkMMMMMyyyyyyykkk",
    ".kkkMMMMyyyyyykkk.",
    "..kkkMMMyyyyykkk..",
    "...kkkMyyyyykkk...",
    "....kkkkkkkkkk....",
    ".....kkkkkkkk.....",
  ],
];

// Every transparent pixel within 2.3px of a drawn one becomes ink: the same
// closed 2px outline, with softened corners, that the hand-drawn props have.
function outline(rows) {
  const h = rows.length;
  const w = rows[0].length;
  const at = (x, y) => (y >= 0 && y < h && x >= 0 && x < w ? rows[y][x] : ".");
  const near = [[-2, -1], [-2, 0], [-2, 1], [-1, -2], [-1, -1], [-1, 0], [-1, 1], [-1, 2], [0, -2], [0, -1], [0, 1], [0, 2], [1, -2], [1, -1], [1, 0], [1, 1], [1, 2], [2, -1], [2, 0], [2, 1]];
  return rows.map((row, y) =>
    row
      .split("")
      .map((ch, x) => (ch === "." && near.some(([i, j]) => at(x + i, y + j) !== ".") ? "k" : ch))
      .join(""),
  );
}

// A ridge of peaks, drawn rather than typed: the skyline is the highest of a
// few triangles, the face right of each apex is shaded, snow sits above a
// jagged line, a couple of 1px creases run down each face, and the outline is
// the same 2px as everything else.
export function mountains(width, height, peaks) {
  const top = Array.from({ length: width }, (_, x) =>
    Math.min(...peaks.map(([apex, h, slope]) => height - h + Math.abs(x - apex) / slope)),
  );
  const rows = [];
  for (let y = 0; y < height; y += 1) {
    let row = "";
    for (let x = 0; x < width; x += 1) {
      if (y < top[x]) {
        row += ".";
        continue;
      }
      const [apex, h] = peaks.reduce((best, p) => {
        const at = height - p[1] + Math.abs(x - p[0]) / p[2];
        return at < best.at ? { at, p } : best;
      }, { at: Infinity, p: peaks[0] }).p;
      const snowLine = height - h + 14 + ((x * 7) % 5) - (Math.abs(x - apex) > 10 ? 3 : 0);
      row += y < snowLine ? "M" : x > apex ? "d" : "m";
    }
    rows.push(row.split(""));
  }
  for (const [apex, h, slope] of peaks) {
    const base = height - h;
    for (let k = 1; k <= 2; k += 1) {
      const x0 = apex + 2 * k;
      const y0 = base + 18 + 4 * k;
      const x1 = Math.min(width - 3, x0 + Math.round((height - 4 - y0) * slope * 0.55));
      const steps = Math.max(1, Math.abs(x1 - x0), height - 4 - y0);
      for (let i = 0; i <= steps; i += 1) {
        const x = Math.round(x0 + ((x1 - x0) * i) / steps);
        const y = Math.round(y0 + ((height - 4 - y0) * i) / steps);
        if (rows[y] && rows[y][x] !== ".") rows[y][x] = "d";
      }
    }
  }
  return outline(rows.map((r) => r.join("")));
}

// The ridge on the map, 240x100: three peaks, the middle one highest.
export const ridge = mountains(240, 100, [
  [48, 66, 0.85],
  [118, 94, 0.7],
  [196, 60, 0.95],
]);
