// Justin, ~62px tall. Each frame is an array of rows, one character per pixel;
// `palette` maps a character to a colour (null = transparent). Standing actions
// share a 36x62 canvas with two spare top rows so the walk can bob 2px. The site
// renders the sheet at half scale, so one on-page px is a 2x2 block here.

const ink = "#1e1711"; // near-black warm brown, darker than --ss-ink so a 2px outline holds at true size; never pure black
const hair = "#563f33"; // dark warm brown, 1.8:1 off the ink so it reads as hair, not outline
const hairLight = "#7c614c"; // strand highlights and the lit rim along the back of the head
const skin = "#e8b98f";
const skinShade = "#cf9a6c";
const straw = "#d9b25a";
const strawLight = "#e8c878"; // sun on the crown
const strawShade = "#b8903f";
const hatBand = "#6e3b2e";
const shirt = "#e4d4b4"; // oat, the plain shirt under the open over-shirt
const overshirt = "#a8674a"; // rust
const overshirtCheck = "#8f5439"; // the windowpane check and seams on the over-shirt
const hoodie = "#5b6579"; // slate, evening layer
const hoodShade = "#48505f"; // the hood's edge on the shoulders and the collar line, hoodie only
const cord = "#f1ede4"; // hoodie drawstrings: cool off-white, so they never read as skin
const aglet = "#1e1711"; // drawstring tips
const pants = "#6a6259"; // warm grey wool
const pantsWeave = "#5b544c";
const pantsCrease = "#7d756b"; // the light edge of a fold
const pantsFar = "#524b44"; // the far leg in the walk, one step back
const shoes = "#54423a";
const shoesFar = "#4a3a31"; // the far shoe in the walk: darker than the near shoe, 1.6:1 off the ink so the foot reads at 1x
const earring = "#7a7f88"; // gunmetal stud on the ear lobe
const teeth = "#efe3cf";
const mouth = "#9b5038"; // warm red-brown smile line (mouth option B, provisional)
const cup = "#efe3cf";
const espresso = "#4a2e1e";

const palette = {
  ".": null,
  k: ink,
  h: hair,
  i: hairLight,
  s: skin,
  d: skinShade,
  y: straw,
  Y: strawLight,
  z: strawShade,
  b: hatBand,
  S: shirt,
  O: overshirt,
  P: overshirtCheck,
  N: shirt, // hoodie collar line: oat on oat by day, so it only shows on the hoodie
  D: shirt, // hoodie drawstrings, likewise
  A: shirt, // drawstring aglets, likewise
  G: overshirt, // hood edge on the shoulders: rust on rust by day, a shade line by night
  H: null, // hood fill: only the hoodie outfit paints these
  J: null, // hood outline
  p: pants,
  q: pantsWeave,
  l: pantsCrease,
  n: pantsFar,
  f: shoes,
  v: shoesFar,
  r: earring,
  w: teeth,
  m: mouth,
  c: cup,
  o: espresso,
};

// Outfits are palette overrides. The hoodie closes the over-shirt (S/O/P all go
// slate) and paints the hood pixels that the day outfit leaves transparent.
const outfits = {
  overshirt: {},
  hoodie: { S: hoodie, O: hoodie, P: hoodie, G: hoodShade, H: hoodie, J: ink, N: hoodShade, D: cord, A: aglet },
};

const idle = [
  [
    "....................................",
    "....................................",
    "..............kkkkkkkk..............",
    "............kkkkkkkkkkkk............",
    "...........kkkkyyyyyykkkk...........",
    "..........kkkyyyyyyyyyykkk..........",
    "..........kkyyyyyyyyyyyykk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    ".....kkkkkkkyyyyyyyyyyyykkkkkkk.....",
    "....kkyyzyyyyyyyzyyyyyyzyyyyyykk....",
    "....kkyyyyyyyyyyyyyyyyyyyyyyyykk....",
    "....kkkkkzzzzzzzzzzzzzzzzzzkkkkk....",
    ".....kkkkkzzzzzzzzzzzzzzzzkkkkk.....",
    "........kkhhhiiiihhhhhhhhhkk........",
    ".......kkkhiihhhhhiihhhhhhkkk.......",
    "......kkkhhhhhhhiihhhhhhiihkkk......",
    "......kkhhhhsshihhsshhhhsshhkk......",
    "......kkhhhhsshhhssshhhssshhkk......",
    "......kkhksssshhsssssshssskhkk......",
    ".....kkssdssswkssssswkssssdsskk.....",
    ".....kkssdssskkssssskkssssdsskk.....",
    ".....kkdskssssssssdssssssskrdkk.....",
    ".....kkkkkksssmssssssmssskkkkkk.....",
    ".........kkssssmmmmmmsssskk.........",
    ".........kkksssssssssssskkk.........",
    "..........kkkksssssssskkkk..........",
    "........JJJkkkksssssskkkkJJJ........",
    ".......JJHHHHkkdssssdkkHHHHJJ.......",
    "......JJHHHHHkkdssssdkkHHHHHJJ......",
    ".....kkkkkkkkkksssssskkkkkkkkkk.....",
    "....kkkkkkkkkkNNNNNNNNkkkkkkkkkk....",
    "....kkGGGGkOOPSSDSSDSSPOOkGGGGkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkOOOOkk....",
    "....kkOOOOkPPPSSASSDSSPPPkOOOOkk....",
    "....kkOOOOkOOPSSSSSASSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkPPPSSSSSSSSPPPkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkkkkkkPPPSSSSSSSSPPPkkkkkkk....",
    "....kksssskOOPSSSSSSSSPOOksssskk....",
    "....kksssskOOPSSSSSSSSPOOksssskk....",
    "....kkkkkkppppppppppppppppkkkkkk....",
    ".....kkppppppppppppppppppppppkk.....",
    "....kkkpppqppppppppppppppppppkkk....",
    "....kkppppqpppppkkkkppppppppppkk....",
    "....kkppppqppppkkkkkkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkppppppqppkk..kkpppqppppkkk....",
    "....kkppppppqppkk..kkqqqqqqqqkk.....",
    "....kkkqqqqqqqkkk..kkkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkkkkkkkkkk....kkkkkkkkkkk.....",
    "......kkkkkkkkk......kkkkkkkkk......",
  ],
  [
    "....................................",
    "....................................",
    "..............kkkkkkkk..............",
    "............kkkkkkkkkkkk............",
    "...........kkkkyyyyyykkkk...........",
    "..........kkkyyyyyyyyyykkk..........",
    "..........kkyyyyyyyyyyyykk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    ".....kkkkkkkyyyyyyyyyyyykkkkkkk.....",
    "....kkyyzyyyyyyyzyyyyyyzyyyyyykk....",
    "....kkyyyyyyyyyyyyyyyyyyyyyyyykk....",
    "....kkkkkzzzzzzzzzzzzzzzzzzkkkkk....",
    ".....kkkkkzzzzzzzzzzzzzzzzkkkkk.....",
    "........kkhhhiiiihhhhhhhhhkk........",
    ".......kkkhiihhhhhiihhhhhhkkk.......",
    "......kkkhhhhhhhiihhhhhhiihkkk......",
    "......kkhhhhsshihhsshhhhsshhkk......",
    "......kkhhhhsshhhssshhhssshhkk......",
    "......kkhksssshhsssssshssskhkk......",
    ".....kkssdssssssssssssssssdsskk.....",
    ".....kkssdsssddsssssddssssdsskk.....",
    ".....kkdskssssssssdssssssskrdkk.....",
    ".....kkkkkksssmssssssmssskkkkkk.....",
    ".........kkssssmmmmmmsssskk.........",
    ".........kkksssssssssssskkk.........",
    "..........kkkksssssssskkkk..........",
    "........JJJkkkksssssskkkkJJJ........",
    ".......JJHHHHkkdssssdkkHHHHJJ.......",
    "......JJHHHHHkkdssssdkkHHHHHJJ......",
    ".....kkkkkkkkkksssssskkkkkkkkkk.....",
    "....kkkkkkkkkkNNNNNNNNkkkkkkkkkk....",
    "....kkGGGGkOOPSSDSSDSSPOOkGGGGkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkOOOOkk....",
    "....kkOOOOkPPPSSASSDSSPPPkOOOOkk....",
    "....kkOOOOkOOPSSSSSASSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkPPPSSSSSSSSPPPkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkkkkkkPPPSSSSSSSSPPPkkkkkkk....",
    "....kksssskOOPSSSSSSSSPOOksssskk....",
    "....kksssskOOPSSSSSSSSPOOksssskk....",
    "....kkkkkkppppppppppppppppkkkkkk....",
    ".....kkppppppppppppppppppppppkk.....",
    "....kkkpppqppppppppppppppppppkkk....",
    "....kkppppqpppppkkkkppppppppppkk....",
    "....kkppppqppppkkkkkkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkppppppqppkk..kkpppqppppkkk....",
    "....kkppppppqppkk..kkqqqqqqqqkk.....",
    "....kkkqqqqqqqkkk..kkkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkkkkkkkkkk....kkkkkkkkkkk.....",
    "......kkkkkkkkk......kkkkkkkkk......",
  ],
  [
    "....................................",
    "....................................",
    "..............kkkkkkkk..............",
    "............kkkkkkkkkkkk............",
    "...........kkkkyyyyyykkkk...........",
    "..........kkkyyyyyyyyyykkk..........",
    "..........kkyyyyyyyyyyyykk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    ".....kkkkkkkyyyyyyyyyyyykkkkkkk.....",
    "....kkyyzyyyyyyyzyyyyyyzyyyyyykk....",
    "....kkyyyyyyyyyyyyyyyyyyyyyyyykk....",
    "....kkkkkzzzzzzzzzzzzzzzzzzkkkkk....",
    ".....kkkkkzzzzzzzzzzzzzzzzkkkkk.....",
    "........kkhhhiiiihhhhhhhhhkk........",
    ".......kkkhiihhhhhiihhhhhhkkk.......",
    "......kkkhhhhhhhiihhhhhhiihkkk......",
    "......kkhhhhsshihhsshhhhsshhkk......",
    "......kkhhhhsshhhssshhhssshhkk......",
    "......kkhksssshhsssssshssskhkk......",
    ".....kkssdssswkssssswkssssdsskk.....",
    ".....kkssdssskkssssskkssssdsskk.....",
    ".....kkdskssssssssdssssssskrdkk.....",
    ".....kkkkkksssmssssssmssskkkkkk.....",
    ".........kkssssmmmmmmsssskk.........",
    ".........kkksssssssssssskkk.........",
    "..........kkkksssssssskkkk..........",
    "........JJJkkkksssssskkkkJJJ........",
    ".......JJHHHHkkdssssdkkHHHHJJ.......",
    "......JJHHHHHkkdssssdkkHHHHHJJ......",
    ".....kkkkkkkkkksssssskkkkkkkkkk.....",
    "....kkkkkkkkkkNNNNNNNNkkkkkkkkkk....",
    "....kkGGGGkOOPSSDSSDSSPOOkGGGGkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkOOOOkk....",
    "....kkOOOOkPPPSSASSDSSPPPkOOOOkk....",
    "....kkOOOOkOOPSSSSSASSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkPPPSSSSSSSSPPPkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkOOOOkk....",
    "....kkkkkkkPPPSSSSSSSSPPPkkkkkkk....",
    "....kksssskOOPSSSSSSSSPOOksssskk....",
    "....kksssskOOPSSSSSSSSPOOksssskk....",
    "....kkkkkkppppppppppppppppkkkkkk....",
    ".....kkppppppppppppppppppppppkk.....",
    "....kkkpppqppppppppppppppppppkkk....",
    "....kkppppqpppppkkkkppppppppppkk....",
    "....kkppppqppppkkkkkkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkppppppqppkk..kkpppqppppkkk....",
    "....kkppppppqppkk..kkqqqqqqqqkk.....",
    "....kkkqqqqqqqkkk..kkkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkkkkkkkkkk....kkkkkkkkkkk.....",
    "......kkkkkkkkk......kkkkkkkkk......",
  ],
];

// Side view, facing right: contact (near leg forward), passing (near leg planted,
// far leg swinging through), contact (far leg forward), passing (far planted). The
// far leg is one step darker and behind. Passing frames lift the body one row; the
// planted foot stays on the ground rows. Drawn for 7px of travel per frame.
const walk = [
  [
    "....................................",
    "....................................",
    "................kkkkkkkk............",
    "..............kkkkkkkkkkkk..........",
    ".............kkkkyyyyyykkkk.........",
    "............kkkyyyyyyyyyykkk........",
    "............kkyyyyyyyyyyyykk........",
    "............kkbbbbbbbbbbbbkk........",
    "............kkbbbbbbbbbbbbkk........",
    ".......kkkkkkkyyyyyyyyyyyykkkkkkk...",
    "......kkyyzyyyyyyyzyyyyyyzyyyyyykk..",
    "......kkyyyyyyyyyyyyyyyyyyyyyyyykk..",
    "......kkkkzzzzzzzzzzzzzzzzzzzzkkkk..",
    ".......kkkkzzzzzzzzzzzzzzzzzzkkkk...",
    ".........kkhhhhhhhhhhhhhhhhhkkk.....",
    "........kkhhhiihhhhhiihhhhhhhkk.....",
    ".......kkhhhhhhhiihhhhhhiihhhkk.....",
    ".......kkhhiihhhhhhhhhhhhhhsskk.....",
    "........kkhhhhhhhhhiihhhhshhskk.....",
    "........kkhhhhhhhhhhhhshhswkskk.....",
    ".........kkhhhhhhhkkksssssskskk.....",
    "..........kkhhhhhhkdssssssssskk.....",
    ".........kkhhhhhhhkdrssssssssskk....",
    "..........kkkhhhhhkkksssssssskk.....",
    "...........kkkddsssssssssssdkkk.....",
    ".............kkdssssssssssssskk.....",
    "..........JJJkkddssskkssssskkk......",
    ".........JJJHkkddssskkkkkkkkkk......",
    "........JJHHHkkddssskkkkkkkkk.......",
    "........JJHHHkkddssskk..............",
    "........kkkkkkkOOkkkkkkkkkk.........",
    "..........kkkkkOOOOOkkkkkkk.........",
    "..........kkGGkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOkOOOOOkOOPSSkk.........",
    "..........kkOkOOOOOkOOPSSkk.........",
    "..........kkOkOOPOOkOOPSSkk.........",
    "..........kkOkOOOOOkOOPSSkk.........",
    "..........kkkOOOOOkOOOPSSkk.........",
    "..........kkkOOOOOkOOOPSSkk.........",
    "..........kkkOOOOOkOOOPSSkk.........",
    "..........kkOOOOOkOOOOPSSkk.........",
    "..........kkkkkkkkOOOOPSSkk.........",
    "..........kkssssskOOOOPSSkk.........",
    "..........kkssssskOOOOPSSkk.........",
    ".........kkkppppppppppppkkkkk.......",
    "..........kknnkpppppppppkk..........",
    "..........kknnnkppppppppkkk.........",
    ".........kkknnnnkpppppqppkkk........",
    ".........kknnnnnnkpppppqppkkk.......",
    "........kkknnnnnkkkpppppqppkkk......",
    "........kknnnnnkkkkkppppqpppkk......",
    ".......kkknnnnnkk.kkpppppqppkkk.....",
    ".......kknnnnnnkk.kkpppppqpppkk.....",
    "......kkknnnnnnkk.kkppppppqppkkk....",
    "......kknnnnnnnkk.kkppppppppppkk....",
    "......kknnnnnnnkk.kkkqqqqqqqqqkk....",
    ".....kkvvvvvvvvvkk.kkfffffffffkk....",
    ".....kkvvvvvvvvvkk.kkfffffffffkk....",
    ".....kkkkkkkkkkkkk.kkkkkkkkkkkkk....",
    "......kkkkkkkkkkk...kkkkkkkkkkk.....",
  ],
  [
    "....................................",
    "................kkkkkkkk............",
    "..............kkkkkkkkkkkk..........",
    ".............kkkkyyyyyykkkk.........",
    "............kkkyyyyyyyyyykkk........",
    "............kkyyyyyyyyyyyykk........",
    "............kkbbbbbbbbbbbbkk........",
    "............kkbbbbbbbbbbbbkk........",
    ".......kkkkkkkyyyyyyyyyyyykkkkkkk...",
    "......kkyyzyyyyyyyzyyyyyyzyyyyyykk..",
    "......kkyyyyyyyyyyyyyyyyyyyyyyyykk..",
    "......kkkkzzzzzzzzzzzzzzzzzzzzkkkk..",
    ".......kkkkzzzzzzzzzzzzzzzzzzkkkk...",
    ".........kkhhhhhhhhhhhhhhhhhkkk.....",
    "........kkhhhiihhhhhiihhhhhhhkk.....",
    ".......kkhhhhhhhiihhhhhhiihhhkk.....",
    ".......kkhhiihhhhhhhhhhhhhhsskk.....",
    "........kkhhhhhhhhhiihhhhshhskk.....",
    "........kkhhhhhhhhhhhhshhswkskk.....",
    ".........kkhhhhhhhkkksssssskskk.....",
    "..........kkhhhhhhkdssssssssskk.....",
    ".........kkhhhhhhhkdrssssssssskk....",
    "..........kkkhhhhhkkksssssssskk.....",
    "...........kkkddsssssssssssdkkk.....",
    ".............kkdssssssssssssskk.....",
    "..........JJJkkddssskkssssskkk......",
    ".........JJJHkkddssskkkkkkkkkk......",
    "........JJHHHkkddssskkkkkkkkk.......",
    "........JJHHHkkddssskk..............",
    "........kkkkkkkOOkkkkkkkkkk.........",
    "..........kkkkkOOOOOkkkkkkk.........",
    "..........kkGGkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOPOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOPOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOPOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkkkkkkkOPSSkk.........",
    "..........kkOOkssssskOPSSkk.........",
    "..........kkOOkssssskOPkkkk.........",
    ".........kkkkpppppppppkkkkkkk.......",
    "...........kkpppppppppkk............",
    "...........kkpppppppppkkk...........",
    "...........kkppqpppppppkkk..........",
    "...........kkppqpppppppkkkkk........",
    "...........kkppqpppppppknkkkk.......",
    "...........kkppqpppppppknnnkkk......",
    "...........kkpppqppppppknnnnkk......",
    "...........kkpppqppppppknnnnkk......",
    "...........kkpppqppppppknnnnkk......",
    "...........kkppppppppppvvvvvkkk.....",
    "...........kkppppppppppvvvvvvkk.....",
    "...........kkkqqqqqqqqqkkkkkkkk.....",
    "............kkfffffffffkkkkkkk......",
    "............kkfffffffffkk...........",
    "............kkkkkkkkkkkkk...........",
    ".............kkkkkkkkkkk............",
  ],
  [
    "....................................",
    "....................................",
    "................kkkkkkkk............",
    "..............kkkkkkkkkkkk..........",
    ".............kkkkyyyyyykkkk.........",
    "............kkkyyyyyyyyyykkk........",
    "............kkyyyyyyyyyyyykk........",
    "............kkbbbbbbbbbbbbkk........",
    "............kkbbbbbbbbbbbbkk........",
    ".......kkkkkkkyyyyyyyyyyyykkkkkkk...",
    "......kkyyzyyyyyyyzyyyyyyzyyyyyykk..",
    "......kkyyyyyyyyyyyyyyyyyyyyyyyykk..",
    "......kkkkzzzzzzzzzzzzzzzzzzzzkkkk..",
    ".......kkkkzzzzzzzzzzzzzzzzzzkkkk...",
    ".........kkhhhhhhhhhhhhhhhhhkkk.....",
    "........kkhhhiihhhhhiihhhhhhhkk.....",
    ".......kkhhhhhhhiihhhhhhiihhhkk.....",
    ".......kkhhiihhhhhhhhhhhhhhsskk.....",
    "........kkhhhhhhhhhiihhhhshhskk.....",
    "........kkhhhhhhhhhhhhshhswkskk.....",
    ".........kkhhhhhhhkkksssssskskk.....",
    "..........kkhhhhhhkdssssssssskk.....",
    ".........kkhhhhhhhkdrssssssssskk....",
    "..........kkkhhhhhkkksssssssskk.....",
    "...........kkkddsssssssssssdkkk.....",
    ".............kkdssssssssssssskk.....",
    "..........JJJkkddssskkssssskkk......",
    ".........JJJHkkddssskkkkkkkkkk......",
    "........JJHHHkkddssskkkkkkkkk.......",
    "........JJHHHkkddssskk..............",
    "........kkkkkkkOOkkkkkkkkkk.........",
    "..........kkkkkOOOOOkkkkkkk.........",
    "..........kkGGkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOOkOOOOOkPSSkk.........",
    "..........kkOOOkOOOOOkPSSkk.........",
    "..........kkOOOkOOPOOkPSSkk.........",
    "..........kkOOOkOOOOOkPSSkk.........",
    "..........kkOOOOkOOOOOkSSkk.........",
    "..........kkOOOOkOOOOOkSSkk.........",
    "..........kkOOOOkOOOOOkSSkk.........",
    "..........kkOOOOOkOOOOOkSkk.........",
    "..........kkOOOOOkkkkkkkSkk.........",
    "..........kkOOOOOkssssskSkk.........",
    "..........kkOOOOOkssssskkkk.........",
    ".........kkkpppppppppppkkkkkk.......",
    "..........kkppppppppknnkk...........",
    "..........kkppppppppknnkkk..........",
    ".........kkkpqpppppknnnnkkk.........",
    ".........kkppqpppppknnnnnkkk........",
    "........kkkpqppppkkknnnnnnkkk.......",
    "........kkppqpppkkkkknnnnnnkk.......",
    ".......kkkpqppppkk.kknnnnnnkkk......",
    ".......kkppqppppkk.kknnnnnnnkk......",
    "......kkkpqpppppkk.kknnnnnnnkkk.....",
    "......kkppppppppkk.kknnnnnnnnkk.....",
    "......kkqqqqqqqqkk.kknnnnnnnnkk.....",
    ".....kkfffffffffkk.kkvvvvvvvvvkk....",
    ".....kkfffffffffkk.kkvvvvvvvvvkk....",
    ".....kkkkkkkkkkkkk.kkkkkkkkkkkkk....",
    "......kkkkkkkkkkk...kkkkkkkkkkk.....",
  ],
  [
    "....................................",
    "................kkkkkkkk............",
    "..............kkkkkkkkkkkk..........",
    ".............kkkkyyyyyykkkk.........",
    "............kkkyyyyyyyyyykkk........",
    "............kkyyyyyyyyyyyykk........",
    "............kkbbbbbbbbbbbbkk........",
    "............kkbbbbbbbbbbbbkk........",
    ".......kkkkkkkyyyyyyyyyyyykkkkkkk...",
    "......kkyyzyyyyyyyzyyyyyyzyyyyyykk..",
    "......kkyyyyyyyyyyyyyyyyyyyyyyyykk..",
    "......kkkkzzzzzzzzzzzzzzzzzzzzkkkk..",
    ".......kkkkzzzzzzzzzzzzzzzzzzkkkk...",
    ".........kkhhhhhhhhhhhhhhhhhkkk.....",
    "........kkhhhiihhhhhiihhhhhhhkk.....",
    ".......kkhhhhhhhiihhhhhhiihhhkk.....",
    ".......kkhhiihhhhhhhhhhhhhhsskk.....",
    "........kkhhhhhhhhhiihhhhshhskk.....",
    "........kkhhhhhhhhhhhhshhswkskk.....",
    ".........kkhhhhhhhkkksssssskskk.....",
    "..........kkhhhhhhkdssssssssskk.....",
    ".........kkhhhhhhhkdrssssssssskk....",
    "..........kkkhhhhhkkksssssssskk.....",
    "...........kkkddsssssssssssdkkk.....",
    ".............kkdssssssssssssskk.....",
    "..........JJJkkddssskkssssskkk......",
    ".........JJJHkkddssskkkkkkkkkk......",
    "........JJHHHkkddssskkkkkkkkk.......",
    "........JJHHHkkddssskk..............",
    "........kkkkkkkOOkkkkkkkkkk.........",
    "..........kkkkkOOOOOkkkkkkk.........",
    "..........kkGGkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOPOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOPOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOPOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkOOOOOkOPSSkk.........",
    "..........kkOOkkkkkkkOPSSkk.........",
    "..........kkOOkssssskOPSSkk.........",
    "..........kkkOkssssskOPSkkk.........",
    ".........kkkkkpppppppppkkkkkk.......",
    "............kkpppppppppkk...........",
    "............kkkppppppppkkk..........",
    "............kknkppppppppkkk.........",
    "............kknnkppppppppkkk........",
    "............kknnnkppppppppkkk.......",
    "............kknnnnkppppppppkk.......",
    "............kknnnnkppppqpppkk.......",
    "............kknnnnkppppqpppkk.......",
    "............kknnnkqqqqqqqqqkk.......",
    "............kknnnnnkffffffffkkk.....",
    "............kknnnnnkffffffffkkk.....",
    "............kknnnnnkkkkkkkkkkkk.....",
    "............kkvvvvvvvvvkkkkkkk......",
    "............kkvvvvvvvvvkk...........",
    "............kkkkkkkkkkkkk...........",
    ".............kkkkkkkkkkk............",
  ],
];

// Sitting on the ground, side view, legs out in front, hand on the thigh. Two frames:
// eyes open, then a short blink.
const sit = [
  [
    "................kkkkkkkk............................",
    "..............kkkkkkkkkkkk..........................",
    ".............kkkkyyyyyykkkk.........................",
    "............kkkyyyyyyyyyykkk........................",
    "............kkyyyyyyyyyyyykk........................",
    "............kkbbbbbbbbbbbbkk........................",
    "............kkbbbbbbbbbbbbkk........................",
    ".......kkkkkkkyyyyyyyyyyyykkkkkkk...................",
    "......kkyyzyyyyyyyzyyyyyyzyyyyyykk..................",
    "......kkyyyyyyyyyyyyyyyyyyyyyyyykk..................",
    "......kkkkzzzzzzzzzzzzzzzzzzzzkkkk..................",
    ".......kkkkzzzzzzzzzzzzzzzzzzkkkk...................",
    ".........kkhhhhhhhhhhhhhhhhhkkk.....................",
    "........kkhhhiihhhhhiihhhhhhhkk.....................",
    ".......kkhhhhhhhiihhhhhhiihhhkk.....................",
    ".......kkhhiihhhhhhhhhhhhhhsskk.....................",
    "........kkhhhhhhhhhiihhhhshhskk.....................",
    "........kkhhhhhhhhhhhhshhswkskk.....................",
    ".........kkhhhhhhhkkksssssskskk.....................",
    "..........kkhhhhhhkdssssssssskk.....................",
    ".........kkhhhhhhhkdrssssssssskk....................",
    "..........kkkhhhhhkkksssssssskk.....................",
    "...........kkkddsssssssssssdkkk.....................",
    ".............kkdssssssssssssskk.....................",
    "..........JJJkkddssskkssssskkk......................",
    ".........JJJHkkddssskkkkkkkkkk......................",
    "........JJHHHkkddssskkkkkkkkk.......................",
    "........JJHHHkkddssskk..............................",
    "........kkkkkkkOOkkkkkkkkkk.........................",
    "..........kkkkOOOOOOOkkkkkk.........................",
    "..........kkGkOOOOOkOOPSSkk.........................",
    "..........kkOkOOOOOkOOPSSkk.........................",
    "..........kkOkOOOOOkOOPSSkk.........................",
    "..........kkOkOOOOOOkOPSSkk.........................",
    "..........kkOOkOOOOOOkPSSkk.........................",
    "..........kkOOOkOOOOOOkSSkk.........................",
    "..........kkOOOOkOOOOOOkSkk.........................",
    "..........kkOOOOOkOOOOOOkkk.........................",
    "..........kkOOOOOOkOOOOOOkk.........................",
    "..........kkOOOOOOOkOOOOOkk.........................",
    "..........kkOOOOOOOOkOOOOkkk........................",
    "..........kkOOOOOOOOOkkkkkkkk................kkk....",
    "..........kkOOOOOOOOOOksssskkkkkkkkk........kkkkk...",
    "..........kkOOOOOOOOOOkssssskkkkkkkkk.......kffkk...",
    "..........kkppppppppppkssssssppppppkkk.....kkffkk...",
    "..........kkppppqppppppppppppqppppppkkk....kkffkk...",
    "..........kkppqpppppppppplpppppqpppppkkk..kkfffkk...",
    "..........kkpppppppppqpppppppppplpppppkkkkkkfffkk...",
    "..........kkpppppppppppppqpppppppppqpppkkkkffffkk...",
    "..........kkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkffffkk...",
    "..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
    "...........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  ],
  [
    "................kkkkkkkk............................",
    "..............kkkkkkkkkkkk..........................",
    ".............kkkkyyyyyykkkk.........................",
    "............kkkyyyyyyyyyykkk........................",
    "............kkyyyyyyyyyyyykk........................",
    "............kkbbbbbbbbbbbbkk........................",
    "............kkbbbbbbbbbbbbkk........................",
    ".......kkkkkkkyyyyyyyyyyyykkkkkkk...................",
    "......kkyyzyyyyyyyzyyyyyyzyyyyyykk..................",
    "......kkyyyyyyyyyyyyyyyyyyyyyyyykk..................",
    "......kkkkzzzzzzzzzzzzzzzzzzzzkkkk..................",
    ".......kkkkzzzzzzzzzzzzzzzzzzkkkk...................",
    ".........kkhhhhhhhhhhhhhhhhhkkk.....................",
    "........kkhhhiihhhhhiihhhhhhhkk.....................",
    ".......kkhhhhhhhiihhhhhhiihhhkk.....................",
    ".......kkhhiihhhhhhhhhhhhhhsskk.....................",
    "........kkhhhhhhhhhiihhhhshhskk.....................",
    "........kkhhhhhhhhhhhhshhsssskk.....................",
    ".........kkhhhhhhhkkksssssddskk.....................",
    "..........kkhhhhhhkdssssssssskk.....................",
    ".........kkhhhhhhhkdrssssssssskk....................",
    "..........kkkhhhhhkkksssssssskk.....................",
    "...........kkkddsssssssssssdkkk.....................",
    ".............kkdssssssssssssskk.....................",
    "..........JJJkkddssskkssssskkk......................",
    ".........JJJHkkddssskkkkkkkkkk......................",
    "........JJHHHkkddssskkkkkkkkk.......................",
    "........JJHHHkkddssskk..............................",
    "........kkkkkkkOOkkkkkkkkkk.........................",
    "..........kkkkOOOOOOOkkkkkk.........................",
    "..........kkGkOOOOOkOOPSSkk.........................",
    "..........kkOkOOOOOkOOPSSkk.........................",
    "..........kkOkOOOOOkOOPSSkk.........................",
    "..........kkOkOOOOOOkOPSSkk.........................",
    "..........kkOOkOOOOOOkPSSkk.........................",
    "..........kkOOOkOOOOOOkSSkk.........................",
    "..........kkOOOOkOOOOOOkSkk.........................",
    "..........kkOOOOOkOOOOOOkkk.........................",
    "..........kkOOOOOOkOOOOOOkk.........................",
    "..........kkOOOOOOOkOOOOOkk.........................",
    "..........kkOOOOOOOOkOOOOkkk........................",
    "..........kkOOOOOOOOOkkkkkkkk................kkk....",
    "..........kkOOOOOOOOOOksssskkkkkkkkk........kkkkk...",
    "..........kkOOOOOOOOOOkssssskkkkkkkkk.......kffkk...",
    "..........kkppppppppppkssssssppppppkkk.....kkffkk...",
    "..........kkppppqppppppppppppqppppppkkk....kkffkk...",
    "..........kkppqpppppppppplpppppqpppppkkk..kkfffkk...",
    "..........kkpppppppppqpppppppppplpppppkkkkkkfffkk...",
    "..........kkpppppppppppppqpppppppppqpppkkkkffffkk...",
    "..........kkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkffffkk...",
    "..........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
    "...........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  ],
];

// Flat on his back, head left, hat resting on his face, a hand on his belly.
// Reads as three blocks: top layer, pants, shoes with the toes up.
const sleep = [
  [
    ".......kkkkkkk..................................................",
    ".....kkkkkkkkkkk................................................",
    "....kkkkyyyyykkk................................................",
    "...kkkyyyyyyyykkk...............................................",
    "...kkyyyyyyyyyykk...............................................",
    "...kkbbbbbbbbbbkk...............................................",
    "...kkbbbbbbbbbbkk...............................................",
    ".kkkkyyyyyyyyyykkkkkkkk.........................................",
    "kkkkzyyyyyyyzyyykkkkkkkk........................................",
    "kkyyyyyyyyyyyyyyyyyyyykk..................................kkkk..",
    "kkzzzyzzzzzzzzyzzzzzzzkk.............................kkkkkkkkkk.",
    ".kkkkkzzzzzzzzzzzzzzzkk....kkkkkkkkkkkkkkk..........kkkkkkkffkk.",
    "....kkhhhhhsssssssssskkkk.kkkkkkkkkkkkkkkkk.kkkkkkkkkkpppkfffkk.",
    "...kkkhhiiisssssssssssskkkkkOOSSSSSSSSSOOkkkkkkkkkkkkppppkfffkk.",
    "...kkhhiihhssssssssssssdkkkOPOOOOkssssskOOkkkppppppplppppkfffkk.",
    "..kkkhhhhhhkdssssssssssdkkkkkkkkkkssssskOOOkkppqpppppppppkfffkk.",
    ".kkkhhhhhhhkrsssssssssskkkkOOOOOOkssssskOOOkkppppqpppppppkfffkk.",
    "..kkkiihhhhhsssssssssssskkkOOOOOOkkkkkkkOOOkkppppppqpppppkfffkk.",
    "...kkihhhhhhhssssssssssskkkkkkkkkOOOPOOOOOOkkppppppppppppkfffkk.",
    "...kkhihhhhhhhsssssssssskkOOOPOOOOOOPOOOOOOkkpppqppppplppkfffkk.",
    "...kkkhhhhhhhhhddddssssskkOOOPOOOOOOPOOOOOOkkpppppqppppppkfffkk.",
    "....kkhhhhhhhhhhhdddskkkkkOOOPOOOOOOPOOOOOOkkpppppppqppppkfffkk.",
    "....kkhhhiiihhhhdddkkkkkkkkPPPPPPPPPPPPPPPPkkppppppppppppkfffkk.",
    "....kkkhhhhhiihhhddkkk...kkOOPOOOOOOPOOOOOOkkppppqpppppppkfffkk.",
    ".....kkkhhhhhhhhhhkkk....kkOOPOOOOOOPOOOOOOkkppppppppppppkfffkk.",
    "......kkhhhhhhhhhhkk.....kkOOOOOOOOOOOOOOOOkkqqqqqqqqqqqqkfffkk.",
    "..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
  ],
];

// Espresso cup held at the chest, then raised to the grin.
const sip = [
  [
    "....................................",
    "....................................",
    "..............kkkkkkkk..............",
    "............kkkkkkkkkkkk............",
    "...........kkkkyyyyyykkkk...........",
    "..........kkkyyyyyyyyyykkk..........",
    "..........kkyyyyyyyyyyyykk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    ".....kkkkkkkyyyyyyyyyyyykkkkkkk.....",
    "....kkyyzyyyyyyyzyyyyyyzyyyyyykk....",
    "....kkyyyyyyyyyyyyyyyyyyyyyyyykk....",
    "....kkkkkzzzzzzzzzzzzzzzzzzkkkkk....",
    ".....kkkkkzzzzzzzzzzzzzzzzkkkkk.....",
    "........kkhhhiiiihhhhhhhhhkk........",
    ".......kkkhiihhhhhiihhhhhhkkk.......",
    "......kkkhhhhhhhiihhhhhhiihkkk......",
    "......kkhhhhsshihhsshhhhsshhkk......",
    "......kkhhhhsshhhssshhhssshhkk......",
    "......kkhksssshhsssssshssskhkk......",
    ".....kkssdssswkssssswkssssdsskk.....",
    ".....kkssdssskkssssskkssssdsskk.....",
    ".....kkdskssssssssdssssssskrdkk.....",
    ".....kkkkkksssmssssssmssskkkkkk.....",
    ".........kkssssmmmmmmsssskk.........",
    ".........kkksssssssssssskkk.........",
    "..........kkkksssssssskkkk..........",
    "........JJJkkkksssssskkkkJJJ........",
    ".......JJHHHHkkdssssdkkHHHHJJ.......",
    "......JJHHHHHkkdssssdkkHHHHHJJ......",
    ".....kkkkkkkkkksssssskkkkkkkkkk.....",
    "....kkkkkkkkkkNNNNNNNNkkkkkkkkkk....",
    "....kkGGGGkOOPSSDSSDSSPOOkGGGGkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkOOOOkk....",
    "....kkOOOOkOOPSSDSkooookOkOOOOkk....",
    "....kkOOOOkPPPSSASkcccckkkOOOOkk....",
    "....kkOOOOkOOPSSSSkcccckkkOOOOkk....",
    "....kkOOOOkOOPSSSksssssskkkkkkkk....",
    "....kkOOOOkOOPSSSkssssssOOOOOOkk....",
    "....kkOOOOkPPPSSSkssssssOOOkkkkk....",
    "....kkOOOOkOOPSSSkkkkkkkkkkkkkkk....",
    "....kkOOOOkOOPSSSSSSSSPOOOkk........",
    "....kkOOOOkOOPSSSSSSSSPOOOkk........",
    "....kkkkkkkPPPSSSSSSSSPPPPkk........",
    "....kksssskOOPSSSSSSSSPOOOkk........",
    "....kksssskOOPSSSSSSSSPOOOkk........",
    "....kkkkkkppppppppppppppppkk........",
    ".....kkpppppppppppppppppppkkkkk.....",
    "....kkkpppqppppppppppppppppkkkkk....",
    "....kkppppqpppppkkkkppppppppppkk....",
    "....kkppppqppppkkkkkkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkppppppqppkk..kkpppqppppkkk....",
    "....kkppppppqppkk..kkqqqqqqqqkk.....",
    "....kkkqqqqqqqkkk..kkkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkkkkkkkkkk....kkkkkkkkkkk.....",
    "......kkkkkkkkk......kkkkkkkkk......",
  ],
  [
    "....................................",
    "....................................",
    "..............kkkkkkkk..............",
    "............kkkkkkkkkkkk............",
    "...........kkkkyyyyyykkkk...........",
    "..........kkkyyyyyyyyyykkk..........",
    "..........kkyyyyyyyyyyyykk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    ".....kkkkkkkyyyyyyyyyyyykkkkkkk.....",
    "....kkyyzyyyyyyyzyyyyyyzyyyyyykk....",
    "....kkyyyyyyyyyyyyyyyyyyyyyyyykk....",
    "....kkkkkzzzzzzzzzzzzzzzzzzkkkkk....",
    ".....kkkkkzzzzzzzzzzzzzzzzkkkkk.....",
    "........kkhhhiiiihhhhhhhhhkk........",
    ".......kkkhiihhhhhiihhhhhhkkk.......",
    "......kkkhhhhhhhiihhhhhhiihkkk......",
    "......kkhhhhsshihhsshhhhsshhkk......",
    "......kkhhhhsshhhssshhhssshhkk......",
    "......kkhksssshhsssssshssskhkk......",
    ".....kkssdssswkssssswkssssdsskk.....",
    ".....kkssdssskkssssskkssssdsskk.....",
    ".....kkdskssssssssdssssssskrdkk.....",
    ".....kkkkkksssmssssssskoookkkkk.....",
    ".........kkssssmmmmssskcccksskk.....",
    ".........kkksssssssssskcccksskk.....",
    "..........kkkkssssssskkkssssskk.....",
    "........JJJkkkksssssskkksssskk......",
    ".......JJHHHHkkdssssdkkOOOOOkk......",
    "......JJHHHHHkkdssssdkkkOOOOOkkk....",
    ".....kkkkkkkkkksssssskkkkOOOOkkk....",
    "....kkkkkkkkkkNNNNNNNNkkkkkOOOkk....",
    "....kkGGGGkOOPSSDSSDSSPOOkkOOOkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkkOOOkk....",
    "....kkOOOOkOOPSSDSSDSSPOOkkOOOkk....",
    "....kkOOOOkPPPSSASSDSSPPPkkOOOkk....",
    "....kkOOOOkOOPSSSSSASSPOOkkOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkkOOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOkkOOOkk....",
    "....kkOOOOkPPPSSSSSSSSPPPPkkOOkk....",
    "....kkOOOOkOOPSSSSSSSSPOOOkkkkkk....",
    "....kkOOOOkOOPSSSSSSSSPOOOkkkkk.....",
    "....kkOOOOkOOPSSSSSSSSPOOOkk........",
    "....kkkkkkkPPPSSSSSSSSPPPPkk........",
    "....kksssskOOPSSSSSSSSPOOOkk........",
    "....kksssskOOPSSSSSSSSPOOOkk........",
    "....kkkkkkppppppppppppppppkk........",
    ".....kkpppppppppppppppppppkkkkk.....",
    "....kkkpppqppppppppppppppppkkkkk....",
    "....kkppppqpppppkkkkppppppppppkk....",
    "....kkppppqppppkkkkkkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkppppppqppkk..kkpppqppppkkk....",
    "....kkppppppqppkk..kkqqqqqqqqkk.....",
    "....kkkqqqqqqqkkk..kkkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkkkkkkkkkk....kkkkkkkkkkk.....",
    "......kkkkkkkkk......kkkkkkkkk......",
  ],
];

// One hand holding the brim.
const hat = [
  [
    "....................................",
    "....................................",
    "..............kkkkkkkk..............",
    "............kkkkkkkkkkkk............",
    "...........kkkkyyyyyykkkk...........",
    "..........kkkyyyyyyyyyykkk..........",
    "..........kkyyyyyyyyyyyykk..........",
    "..........kkbbbbbbbbbbbbkk..........",
    "..........kkbbbbbbbbbbbbkkkk........",
    ".....kkkkkkkyyyyyyyyyyykkkkkkkk.....",
    "....kkyyzyyyyyyyzyyyyyksssskyykk....",
    "....kkyyyyyyyyyyyyyyyyksssskyykk....",
    "....kkkkkzzzzzzzzzzzzzksssskkkkk....",
    ".....kkkkkzzzzzzzzzzzzzkOOOOOkkk....",
    "........kkhhhiiiihhhhhhikOOOOOkkk...",
    ".......kkkhiihhhhhiihhhhikOOOOOkkk..",
    "......kkkhhhhhhhiihhhhhhiikOOOOOkkk.",
    "......kkhhhhsshihhsshhhhssikOOOOOkkk",
    "......kkhhhhsshhhssshhhssshikOOOOOkk",
    "......kkhksssshhsssssshssskhkOOOOOkk",
    ".....kkssdssswkssssswkssssdsskOOOOkk",
    ".....kkssdssskkssssskkssssdsskOOOOkk",
    ".....kkdskssssssssdssssssskrdkOOOOkk",
    ".....kkkkkksssmssssssmssskkkkkOOOOkk",
    ".........kkssssmmmmmmsssskk.kkOOOOkk",
    ".........kkksssssssssssskkk.kkOOOOkk",
    "..........kkkksssssssskkkk..kkOOOOkk",
    "........JJJkkkksssssskkkkJJJkkOOOOkk",
    ".......JJHHHHkkdssssdkkHHHHJkkOOOOkk",
    "......JJHHHHHkkdssssdkkHHHHHkkOOOOkk",
    ".....kkkkkkkkkksssssskkkkkkkkkOOOOkk",
    "....kkkkkkkkkkNNNNNNNNkkkkkkkOOOOOkk",
    "....kkGGGGkOOPSSDSSDSSPOOOkkkkkkkkkk",
    "....kkOOOOkOOPSSDSSDSSPOOOkkkkkkkkk.",
    "....kkOOOOkOOPSSDSSDSSPOOOkk........",
    "....kkOOOOkPPPSSASSDSSPPPPkk........",
    "....kkOOOOkOOPSSSSSASSPOOOkk........",
    "....kkOOOOkOOPSSSSSSSSPOOOkk........",
    "....kkOOOOkOOPSSSSSSSSPOOOkk........",
    "....kkOOOOkPPPSSSSSSSSPPPPkk........",
    "....kkOOOOkOOPSSSSSSSSPOOOkk........",
    "....kkOOOOkOOPSSSSSSSSPOOOkk........",
    "....kkOOOOkOOPSSSSSSSSPOOOkk........",
    "....kkkkkkkPPPSSSSSSSSPPPPkk........",
    "....kksssskOOPSSSSSSSSPOOOkk........",
    "....kksssskOOPSSSSSSSSPOOOkk........",
    "....kkkkkkppppppppppppppppkk........",
    ".....kkpppppppppppppppppppkkkkk.....",
    "....kkkpppqppppppppppppppppkkkkk....",
    "....kkppppqpppppkkkkppppppppppkk....",
    "....kkppppqppppkkkkkkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkppppppqppkk..kkpppqppppkkk....",
    "....kkppppppqppkk..kkqqqqqqqqkk.....",
    "....kkkqqqqqqqkkk..kkkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkkkkkkkkkk....kkkkkkkkkkk.....",
    "......kkkkkkkkk......kkkkkkkkk......",
  ],
];

// Both arms up.
const armsUp = [
  [
    "....................................",
    "kkkkkkk......................kkkkkkk",
    "kkkkkkk.......kkkkkkkk.......kkkkkkk",
    "kkssskk.....kkkkkkkkkkkk.....kkssskk",
    "kkssskk....kkkkyyyyyykkkk....kkssskk",
    "kkssskk...kkkyyyyyyyyyykkk...kkssskk",
    "kkssskk...kkyyyyyyyyyyyykk...kkssskk",
    "kkkkkkk...kkbbbbbbbbbbbbkk...kkkkkkk",
    "kkOOOkk...kkbbbbbbbbbbbbkk...kkOOOkk",
    "kkOOOkkkkkkkyyyyyyyyyyyykkkkkkkOOOkk",
    "kkOOOkyyzyyyyyyyzyyyyyyzyyyyyykOOOkk",
    "kkOOOkyyyyyyyyyyyyyyyyyyyyyyyykOOOkk",
    "kkOOOkkkkzzzzzzzzzzzzzzzzzzkkkkOOOkk",
    "kkOOOkkkkkzzzzzzzzzzzzzzzzkkkkkOOOkk",
    "kkOOOkkkkkhhhiiiihhhhhhhhhkkkkkOOOkk",
    "kkOOOkkkkkhiihhhhhiihhhhhhkkkkkOOOkk",
    "kkOOOkkkkhhhhhhhiihhhhhhiihkkkkOOOkk",
    "kkOOOkkkhhhhsshihhsshhhhsshhkkkOOOkk",
    "kkOOOkkkhhhhsshhhssshhhssshhkkkOOOkk",
    "kkOOOkkkhksssshhsssssshssskhkkkOOOkk",
    "kkOOOkkssdssswkssssswkssssdsskkOOOkk",
    "kkOOOkkssdssskkssssskkssssdsskkOOOkk",
    "kkOOOkkdskssssssssdssssssskrdkkOOOkk",
    "kkOOOkkkkkksssmssssssmssskkkkkkOOOkk",
    "kkOOOOOOOkkssssmmmmmmsssskkOOOOOOOkk",
    "kkOOOOOOOkkksssssssssssskkkOOOOOOOkk",
    "kkOOOOOOOOkkkksssssssskkkkOOOOOOOOkk",
    "kkOOOOOOOOkkkkksssssskkkkkOOOOOOOOkk",
    "kkOOOOOOOOOOkkkdssssdkkkOOOOOOOOOOkk",
    "kkkkkkkkkOOOkkkdssssdkkkOOOkkkkkkkkk",
    "kkkkkkkkkOOOOSSssssssSSOOOOkkkkkkkkk",
    ".......kkOOOOSNNNNNNNNSOOOOkk.......",
    ".......kkOOOOPSSDSSDSSPOOOOkk.......",
    ".......kkOOOOPSSDSSDSSPOOOOkk.......",
    ".......kkOOOOPSSDSSDSSPOOOOkk.......",
    ".......kkPPPPPSSASSDSSPPPPPkk.......",
    ".......kkOOOOPSSSSSASSPOOOOkk.......",
    ".......kkOOOOPSSSSSSSSPOOOOkk.......",
    ".......kkOOOOPSSSSSSSSPOOOOkk.......",
    ".......kkPPPPPSSSSSSSSPPPPPkk.......",
    ".......kkOOOOPSSSSSSSSPOOOOkk.......",
    ".......kkOOOOPSSSSSSSSPOOOOkk.......",
    ".......kkOOOOPSSSSSSSSPOOOOkk.......",
    ".......kkPPPPPSSSSSSSSPPPPPkk.......",
    ".......kkOOOOPSSSSSSSSPOOOOkk.......",
    ".......kkOOOOPSSSSSSSSPOOOOkk.......",
    "......kkkppppppppppppppppppkkk......",
    ".....kkkppppppppppppppppppppkkk.....",
    "....kkkpppqppppppppppppppppppkkk....",
    "....kkppppqpppppkkkkppppppppppkk....",
    "....kkppppqppppkkkkkkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkppppqppppkk..kkpppppqpppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkpppppqpppkk..kkppppqppppkk....",
    "....kkppppppqppkk..kkpppqppppkkk....",
    "....kkppppppqppkk..kkqqqqqqqqkk.....",
    "....kkkqqqqqqqkkk..kkkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkfffffffkk....kkfffffffkk.....",
    ".....kkkkkkkkkkk....kkkkkkkkkkk.....",
    "......kkkkkkkkk......kkkkkkkkk......",
  ],
];

export default {
  palette,
  outfits,
  actions: {
    idle: { interval: 1200, durations: [1300, 160, 1300], frames: idle },
    walk: { interval: 200, stride: 7, frames: walk },
    sit: { interval: 1200, durations: [3200, 160], frames: sit },
    sleep: { frames: sleep },
    sip: { interval: 1200, durations: [2600, 1000], frames: sip },
    hat: { frames: hat },
    "arms-up": { frames: armsUp },
  },
};
