// luibot, the messenger: a robot in Justin's evening layer and his straw hat.
// 28x32, drawn 1 sprite px = 1 page px: a light blue shell head with a dark
// visor, lit eyes and a mouth light, one ear bolt, and a straight antenna with
// a lit tip poking through the crown; a slate hoodie with the hood down on the
// shoulders, drawstrings and a kangaroo pocket, right hand in the pocket, left
// hand out of the sleeve; wide grey pants over blue metal feet on the last row.
// His attitude is the hat: cocked down over the left eye two rows (the brim and
// crown step down in three segments), so that eye shows half-lidded under the
// brim and the low side hides that ear bolt. The body sits at the right edge
// (brim, torso and feet end at col 27); the seven spare columns on the left are
// for the waving arm. Clothes and hat are Justin's exact colours so the three
// read as one family. Same row-of-characters format and outline rule as
// justin.js: 2px ink around the silhouette, 1px interior lines, 1px on the
// brim's top edge and around the small parts that would vanish under 2px
// (antenna light, ear bolt, hands, feet), which have their own letters.

const ink = "#1e1711"; // near-black warm brown, same as justin.js; never pure black
const shell = "#8fa9c4"; // light blue head, and the hands
const body = "#5e7fa3"; // blue metal: visor, bolt, feet
const light = "#efe3cf";
const straw = "#d9b25a"; // Justin's hat
const strawShade = "#b8903f";
const hatBand = "#6e3b2e";
const hoodie = "#5b6579"; // Justin's slate hoodie
const hoodShade = "#48505f"; // the hood's edge on the shoulders
const drawstring = "#e4d4b4"; // oat, Justin's shirt colour
const pants = "#6a6259"; // warm grey wool
const pantsCrease = "#7d756b";

const glow = "#e8c878"; // thruster flame under the feet while he flies (justin.js strawLight); 1px rim like the feet
const kraft = "#c9a978"; // the feed sack and the shoeboxes he carries (props.js kraft)
const kraftDeep = "#a68858"; // the sack's hem and the shoebox lid bands (props.js kraftDeep)
const grain = "#a68858"; // feed specks leaving the sack, loose in the air with no outline (props.js grain)

const beam = "#8fa9c4"; // the teleport beam: his shell blue, loose cells with no outline (7.2:1 on the dark page)
const beamCore = "#efe3cf"; // the beam's bright core, one cell wide, loose

const palette = {
  ".": null,
  k: ink,
  L: shell,
  m: shell, // hands
  b: body,
  e: body, // ear bolt and feet
  w: light,
  y: straw,
  z: strawShade,
  n: hatBand,
  H: hoodie,
  G: hoodShade,
  D: drawstring,
  p: pants,
  l: pantsCrease,
  a: glow,
  x: kraft,
  X: kraftDeep,
  g: grain,
  Z: beam,
  V: beamCore,
};

// Standing; the feet never leave row 31. The blink darkens the eyes (rows
// 13-14) for one short frame every few seconds; nothing else moves.
const open = [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "........kkLLLLLLLLLLLLLLkk..",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......kkkkkGGGGGGGGGGGkkkkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......kkHHkHHHHHHHHHHHkkkkk",
    "......kkkkkkHHHHHHHHHHHkk...",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......kmmmkppppk..kppppkk...",
    "......kkkkkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
];
const blink = open.map((row, y) => (y === 13 || y === 14 ? row.replace(/w/g, "b") : row));

// Wave: idle's body from col 12 rightward, pixel for pixel, with the left
// sleeve raised: a short thick sleeve (3px of slate between its lines) runs
// from the shoulder up beside the head, bends at the elbow beside the chin,
// and ends in a rounded mitten with a thumb notch on the brim side. Frame A
// holds the hand beside the brim's low tip (cols 0-5, rows 8-13), frame B
// swings it up and in over the tip (cols 3-8, rows 5-10; the mitten's cut
// corner keeps it clear of the brim), the elbow rising with it and the arm
// straightening; one clear column between arm and hat in both frames. The
// right hand stays in the pocket.
const wave = [
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    ".kkkk......kkynnnnnnnkk.....",
    "kkmmkk.....kknnnnnnnykkkkkkk",
    "kmmmmk.....kknyyyyyyyyyzyykk",
    "kmmmkk.kkkkkkyyyyyyyzzzzkkkk",
    "kkmmkk.kyzyyyyzzzzzzLLLLkk..",
    ".kkkkk.kkkzzzzbbbbbbwwbLkkkk",
    ".kHHHk..kkLbwwbbbbbbwwbLkkek",
    ".kHHHk..kkLbbbbbbbbbbbbLkkek",
    ".kHHHkk.kkLbbbbbwwbbbbbLkkkk",
    ".kkHHHkkkkLLLLLLLLLLLLLLkk..",
    "..kkHHHkkkkkkkkkkkkkkkkkkk..",
    "...kkHHHHkkkGGGGGGGGGGGkkkkk",
    "....kkkHHHHkHHHHDHDHHHHkHHkk",
    ".....kkkkkkkHHHHDHDHHHHkHHkk",
    "..........kkHHHHHHHHHHHkHHkk",
    "..........kkHkkkkkkkkkHkHHkk",
    "..........kkHHHHHHHHHHHkkkkk",
    "..........kkHHHHHHHHHHHkk...",
    "..........kkkkkkkkkkkkkkk...",
    ".........kkppppk..kppppkk...",
    ".........kkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
  ],
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "....kkkk......kkkkkkkkk.....",
    "...kkmmkk..kkkkyyyyyykk.....",
    "...kmmmmk..kkyyyyyyynkk.....",
    "...kmmmmk..kkynnnnnnnkk.....",
    "...kmmkkk..kknnnnnnnykkkkkkk",
    ".kkkkkk....kknyyyyyyyyyzyykk",
    ".kHHHk.kkkkkkyyyyyyyzzzzkkkk",
    ".kHHHk.kyzyyyyzzzzzzLLLLkk..",
    ".kHHHk.kkkzzzzbbbbbbwwbLkkkk",
    ".kHHHkk.kkLbwwbbbbbbwwbLkkek",
    ".kkHHHk.kkLbbbbbbbbbbbbLkkek",
    "..kkHHkkkkLbbbbbwwbbbbbLkkkk",
    "...kkHHHkkLLLLLLLLLLLLLLkk..",
    "....kkHHkkkkkkkkkkkkkkkkkk..",
    ".....kkHHHkkGGGGGGGGGGGkkkkk",
    "......kkkHHkHHHHDHDHHHHkHHkk",
    "........kkkkHHHHDHDHHHHkHHkk",
    "..........kkHHHHHHHHHHHkHHkk",
    "..........kkHkkkkkkkkkHkHHkk",
    "..........kkHHHHHHHHHHHkkkkk",
    "..........kkHHHHHHHHHHHkk...",
    "..........kkkkkkkkkkkkkkk...",
    ".........kkppppk..kppppkk...",
    ".........kkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
  ],
];

// Fly: he hovers. Canvas 28x37: idle's body cell for cell in rows 0-31 (feet on
// row 31 as ever), and a thruster flame under each foot in rows 32-36 that
// flickers between a long flame and a short bright one every 260 ms. A design lifts the
// canvas to the height it wants; the feet row is where he would stand. Both
// facings come from `flip`.
const luibotFly = [
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "........kkLLLLLLLLLLLLLLkk..",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......kkkkkGGGGGGGGGGGkkkkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......kkHHkHHHHHHHHHHHkkkkk",
    "......kkkkkkHHHHHHHHHHHkk...",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......kmmmkppppk..kppppkk...",
    "......kkkkkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
    ".........kaaaaak..kaaaaak...",
    "..........kaaak....kaaak....",
    "..........kaaak....kaaak....",
    "...........kak......kak.....",
    "............k........k......",
  ],
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "........kkLLLLLLLLLLLLLLkk..",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......kkkkkGGGGGGGGGGGkkkkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......kkHHkHHHHHHHHHHHkkkkk",
    "......kkkkkkHHHHHHHHHHHkk...",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......kmmmkppppk..kppppkk...",
    "......kkkkkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
    ".........kkwwwkk..kkwwwkk...",
    "..........kaaak....kaaak....",
    "...........kak......kak.....",
    "...........kak......kak.....",
    "............k........k......",
  ],
];

// Fly-wave: `wave`'s two frames with the flames of `fly` under them (28x37),
// for flipping a switch or nudging a chair while he hovers; the waving hand is
// at cols 0-8, rows 5-13.
const luibotFlyWave = [
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    ".kkkk......kkynnnnnnnkk.....",
    "kkmmkk.....kknnnnnnnykkkkkkk",
    "kmmmmk.....kknyyyyyyyyyzyykk",
    "kmmmkk.kkkkkkyyyyyyyzzzzkkkk",
    "kkmmkk.kyzyyyyzzzzzzLLLLkk..",
    ".kkkkk.kkkzzzzbbbbbbwwbLkkkk",
    ".kHHHk..kkLbwwbbbbbbwwbLkkek",
    ".kHHHk..kkLbbbbbbbbbbbbLkkek",
    ".kHHHkk.kkLbbbbbwwbbbbbLkkkk",
    ".kkHHHkkkkLLLLLLLLLLLLLLkk..",
    "..kkHHHkkkkkkkkkkkkkkkkkkk..",
    "...kkHHHHkkkGGGGGGGGGGGkkkkk",
    "....kkkHHHHkHHHHDHDHHHHkHHkk",
    ".....kkkkkkkHHHHDHDHHHHkHHkk",
    "..........kkHHHHHHHHHHHkHHkk",
    "..........kkHkkkkkkkkkHkHHkk",
    "..........kkHHHHHHHHHHHkkkkk",
    "..........kkHHHHHHHHHHHkk...",
    "..........kkkkkkkkkkkkkkk...",
    ".........kkppppk..kppppkk...",
    ".........kkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
    ".........kaaaaak..kaaaaak...",
    "..........kaaak....kaaak....",
    "..........kaaak....kaaak....",
    "...........kak......kak.....",
    "............k........k......",
  ],
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "....kkkk......kkkkkkkkk.....",
    "...kkmmkk..kkkkyyyyyykk.....",
    "...kmmmmk..kkyyyyyyynkk.....",
    "...kmmmmk..kkynnnnnnnkk.....",
    "...kmmkkk..kknnnnnnnykkkkkkk",
    ".kkkkkk....kknyyyyyyyyyzyykk",
    ".kHHHk.kkkkkkyyyyyyyzzzzkkkk",
    ".kHHHk.kyzyyyyzzzzzzLLLLkk..",
    ".kHHHk.kkkzzzzbbbbbbwwbLkkkk",
    ".kHHHkk.kkLbwwbbbbbbwwbLkkek",
    ".kkHHHk.kkLbbbbbbbbbbbbLkkek",
    "..kkHHkkkkLbbbbbwwbbbbbLkkkk",
    "...kkHHHkkLLLLLLLLLLLLLLkk..",
    "....kkHHkkkkkkkkkkkkkkkkkk..",
    ".....kkHHHkkGGGGGGGGGGGkkkkk",
    "......kkkHHkHHHHDHDHHHHkHHkk",
    "........kkkkHHHHDHDHHHHkHHkk",
    "..........kkHHHHHHHHHHHkHHkk",
    "..........kkHkkkkkkkkkHkHHkk",
    "..........kkHHHHHHHHHHHkkkkk",
    "..........kkHHHHHHHHHHHkk...",
    "..........kkkkkkkkkkkkkkk...",
    ".........kkppppk..kppppkk...",
    ".........kkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
    ".........kkwwwkk..kkwwwkk...",
    "..........kaaak....kaaak....",
    "...........kak......kak.....",
    "...........kak......kak.....",
    "............k........k......",
  ],
];

// Feed: hovering, the left arm out and down holding a small kraft sack upside
// down; grain falls from its mouth at x2-4, rows 32-36. Canvas 28x37, body as in
// `fly`. The falling grain continues in the props `feed` prop: put its canvas at
// this canvas's x + 0 with its bottom row on the ground under him. Never stage
// an animal directly under him (his jets would land on her back); she stands
// beside the falling grain. A design stops the pour when the grain has reached
// the pile (switch him to `fly`), or grain leaves the sack and never lands.
const luibotFeed = [
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "...kkkkkkkLLLLLLLLLLLLLLkk..",
    "....kkkkkkkkkkkkkkkkkkkkkk..",
    "...kkHHHHHHHGGGGGGGGGGGkkkkk",
    "..kkHHHHHHHkHHHHDHDHHHHkHHkk",
    ".kkHHHHkkkkkHHHHDHDHHHHkHHkk",
    ".kkkkkkkkkkkHHHHHHHHHHHkHHkk",
    ".kmmmmk...kkHkkkkkkkkkHkHHkk",
    "kkmmmmk...kkHHHHHHHHHHHkkkkk",
    "kkkkkkk...kkHHHHHHHHHHHkk...",
    "kkkxkkk...kkkkkkkkkkkkkkk...",
    "kkxxxkk..kkppppk..kppppkk...",
    "kkxxxkk..kkppppk..kppppkk...",
    "kkXXXkk..kkpplpk..kplppkk...",
    "kkkkkkk..keeeeek..keeeeek...",
    "kkkkkkk..kkkkkkk..kkkkkkk...",
    "..g.g....kaaaaak..kaaaaak...",
    "...g......kaaak....kaaak....",
    "..g.......kaaak....kaaak....",
    "...g.g.....kak......kak.....",
    "..g.........k........k......",
  ],
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "...kkkkkkkLLLLLLLLLLLLLLkk..",
    "....kkkkkkkkkkkkkkkkkkkkkk..",
    "...kkHHHHHHHGGGGGGGGGGGkkkkk",
    "..kkHHHHHHHkHHHHDHDHHHHkHHkk",
    ".kkHHHHkkkkkHHHHDHDHHHHkHHkk",
    ".kkkkkkkkkkkHHHHHHHHHHHkHHkk",
    ".kmmmmk...kkHkkkkkkkkkHkHHkk",
    "kkmmmmk...kkHHHHHHHHHHHkkkkk",
    "kkkkkkk...kkHHHHHHHHHHHkk...",
    "kkkxkkk...kkkkkkkkkkkkkkk...",
    "kkxxxkk..kkppppk..kppppkk...",
    ".kkxxxkk.kkppppk..kppppkk...",
    ".kkXXXkk.kkpplpk..kplppkk...",
    ".kkkkkkk.keeeeek..keeeeek...",
    ".kkkkkkk.kkkkkkk..kkkkkkk...",
    "...g.g...kkwwwkk..kkwwwkk...",
    "....g.....kaaak....kaaak....",
    "...g.......kak......kak.....",
    "..g..g.....kak......kak.....",
    "....g.......k........k......",
  ],
];

// Fly-carry: hovering with the two shoeboxes from the rack (props `shoeboxes`,
// the same 16x23 cells) hugged in front like Justin's `carry`: top rim at his
// shoulders (row 18), x5-20, both sleeves hanging outside the boxes from under
// their top rim, mittens gripping the sides across the seam between the two
// boxes (rows 28-30; the seam is row 29), as Justin's `carry` grips the bottom
// box. Canvas 28x41: body rows 0-31 as `fly`, boxes rows 18-40 painted over the
// right foot's flame, which shows beside them (x21-24, rows 32-36); the left
// flame is behind them.
const luibotFlyCarry = [
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "........kkLLLLLLLLLLLLLLkk..",
    "kkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "kkkkkkkkkkkkkkkkkkkkGkkkkk..",
    "kkHHHkkXXXXXXXXXXXkkHHHHkk..",
    "kkHHHkkXXXXXXXXXXXkkHHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkHHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkkHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkHHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkHHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkkHHHkk..",
    "kkkkkkkxxxxxxxxxxxkkpkkkkk..",
    "kmmmkkkxxxxxxxxxxxkkpkmmmk..",
    "kmmmkkkkkkkkkkkkkkkkkkmmmk..",
    "kmmmk.kkXXXXXXXXXXXkkkmmmk..",
    "kkkkk.kkXXXXXXXXXXXkkkkkkk..",
    "......kkxxxxxxxxxxxkkaaak...",
    "......kkxxxxxxxxxxxkkaak....",
    "......kkxxxxxxxxxxxkkaak....",
    "......kkxxxxxxxxxxxkkak.....",
    "......kkxxxxxxxxxxxkkk......",
    "......kkxxxxxxxxxxxkk.......",
    "......kkxxxxxxxxxxxkk.......",
    "......kkkkkkkkkkkkkkk.......",
    "......kkkkkkkkkkkkkkk.......",
  ],
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "........kkLLLLLLLLLLLLLLkk..",
    "kkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "kkkkkkkkkkkkkkkkkkkkGkkkkk..",
    "kkHHHkkXXXXXXXXXXXkkHHHHkk..",
    "kkHHHkkXXXXXXXXXXXkkHHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkHHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkkHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkHHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkHHHHkk..",
    "kkHHHkkxxxxxxxxxxxkkkHHHkk..",
    "kkkkkkkxxxxxxxxxxxkkpkkkkk..",
    "kmmmkkkxxxxxxxxxxxkkpkmmmk..",
    "kmmmkkkkkkkkkkkkkkkkkkmmmk..",
    "kmmmk.kkXXXXXXXXXXXkkkmmmk..",
    "kkkkk.kkXXXXXXXXXXXkkkkkkk..",
    "......kkxxxxxxxxxxxkkwwkk...",
    "......kkxxxxxxxxxxxkkaak....",
    "......kkxxxxxxxxxxxkkak.....",
    "......kkxxxxxxxxxxxkkak.....",
    "......kkxxxxxxxxxxxkkk......",
    "......kkxxxxxxxxxxxkk.......",
    "......kkxxxxxxxxxxxkk.......",
    "......kkkkkkkkkkkkkkk.......",
    "......kkkkkkkkkkkkkkk.......",
  ],
];

// Beam-out: the teleport, a one-shot of six frames at 70 ms (420 ms). Same canvas
// (28x32) and body position as `idle` frame 0; the bottom row is painted in every
// frame. beam-out: three scan lines of his colour across the body, the body
// sliced into bands, bars narrowing round a one-cell core, a three-cell column
// of light, the core alone, two cells on the ground; then nothing (the design
// removes him). beam-in is the same in reverse and its last frame IS `idle` frame 0, so
// the design cuts to that rest with no change. Quiet on purpose: no glow wider
// than seven cells, the only light colour is the one-cell core.
const luibotBeamOut = [
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........ZZZZZZZZZZZZZZZZZ",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........ZZZZZZZZZZZZZZZZZZZZ",
    "........kkLLLLLLLLLLLLLLkk..",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......kkkkkGGGGGGGGGGGkkkkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    "......kkkkkkHHHHHHHHHHHkk...",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......kmmmkppppk..kppppkk...",
    "......kkkkkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
  ],
  [
    ".................kkkk.......",
    "............................",
    ".................kkkk.......",
    "..................ZZ........",
    "..................kkkkk.....",
    "............................",
    "...........kkkkyyyyyykk.....",
    "...........ZZZZZZZZZZZZ.....",
    "...........kkynnnnnnnkk.....",
    "............................",
    "...........kknyyyyyyyyyzyykk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kyzyyyyzzzzzzLLLLkk..",
    "............................",
    "........kkLbwwbbbbbbwwbLkkek",
    "........ZZZZZZZZZZZZZZZZZZZZ",
    "........kkLbbbbbwwbbbbbLkkkk",
    "............................",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    "............................",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kkHHkHHHHHHHHHHHkkkkk",
    "............................",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......ZZZZZZZZZZZZZZZZZZZ...",
    "......kkkkkppppk..kppppkk...",
    "............................",
    ".........keeeeek..keeeeek...",
    ".........ZZZZZZZZZZZZZZZZ...",
  ],
  [
    ".................V..........",
    "................ZVZ.........",
    ".................V..........",
    ".................V..........",
    "................ZVZ.........",
    ".................V..........",
    ".................V..........",
    "..............ZZZVZZZ.......",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
  ],
  [
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "..............ZZZVZZZ.......",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
  ],
  [
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    "................ZVZ.........",
  ],
  [
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    ".................Z..........",
    ".................V..........",
  ],
];

// Beam-in: the teleport, a one-shot of six frames at 70 ms (420 ms). Same canvas
// (28x32) and body position as `idle` frame 0; the bottom row is painted in every
// frame. beam-out: three scan lines of his colour across the body, the body
// sliced into bands, bars narrowing round a one-cell core, a three-cell column
// of light, the core alone, two cells on the ground; then nothing (the design
// removes him). beam-in is the same in reverse and its last frame IS `idle` frame 0, so
// the design cuts to that rest with no change. Quiet on purpose: no glow wider
// than seven cells, the only light colour is the one-cell core.
const luibotBeamIn = [
  [
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    ".................Z..........",
    ".................V..........",
  ],
  [
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    "................ZVZ.........",
  ],
  [
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "..............ZZZVZZZ.......",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
  ],
  [
    ".................V..........",
    "................ZVZ.........",
    ".................V..........",
    ".................V..........",
    "................ZVZ.........",
    ".................V..........",
    ".................V..........",
    "..............ZZZVZZZ.......",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
  ],
  [
    ".................kkkk.......",
    "............................",
    ".................kkkk.......",
    "..................ZZ........",
    "..................kkkkk.....",
    "............................",
    "...........kkkkyyyyyykk.....",
    "...........ZZZZZZZZZZZZ.....",
    "...........kkynnnnnnnkk.....",
    "............................",
    "...........kknyyyyyyyyyzyykk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kyzyyyyzzzzzzLLLLkk..",
    "............................",
    "........kkLbwwbbbbbbwwbLkkek",
    "........ZZZZZZZZZZZZZZZZZZZZ",
    "........kkLbbbbbwwbbbbbLkkkk",
    "............................",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    "............................",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kkHHkHHHHHHHHHHHkkkkk",
    "............................",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......ZZZZZZZZZZZZZZZZZZZ...",
    "......kkkkkppppk..kppppkk...",
    "............................",
    ".........keeeeek..keeeeek...",
    ".........ZZZZZZZZZZZZZZZZ...",
  ],
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "........kkLLLLLLLLLLLLLLkk..",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......kkkkkGGGGGGGGGGGkkkkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......kkHHkHHHHHHHHHHHkkkkk",
    "......kkkkkkHHHHHHHHHHHkk...",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......kmmmkppppk..kppppkk...",
    "......kkkkkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
  ],
];

// Beam-out-fly: the teleport, a one-shot of six frames at 70 ms (420 ms). Same canvas
// (28x37) and body position as `fly` frame 0; the bottom row is painted in every
// frame. beam-out: three scan lines of his colour across the body, the body
// sliced into bands, bars narrowing round a one-cell core, a three-cell column
// of light, the core alone, two cells on the ground; then nothing (the design
// removes him). beam-in is the same in reverse and its last frame IS `fly` frame 0, so
// the design cuts to that rest with no change. Quiet on purpose: no glow wider
// than seven cells, the only light colour is the one-cell core.
// For arriving and leaving in the air (the feed spot, the sign switch): the
// flames are part of the body that breaks up, and the column reaches the
// flames' ground row 36; his feet row is 31 as in `fly`.
const luibotBeamOutFly = [
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........ZZZZZZZZZZZZZZZZZ",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "........kkLLLLLLLLLLLLLLkk..",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......kkHHkHHHHHHHHHHHkkkkk",
    "......kkkkkkHHHHHHHHHHHkk...",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......ZZZZZZZZZZZZZZZZZZZ...",
    "......kkkkkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
    ".........kaaaaak..kaaaaak...",
    "..........kaaak....kaaak....",
    "..........kaaak....kaaak....",
    "...........kak......kak.....",
    "............k........k......",
  ],
  [
    ".................ZZZZ.......",
    ".................kwwk.......",
    "............................",
    "..................kk........",
    "..................ZZZZZ.....",
    "..............kkkkkkkkk.....",
    "............................",
    "...........kkyyyyyyynkk.....",
    "...........ZZZZZZZZZZZZ.....",
    "...........kknnnnnnnykkkkkkk",
    "............................",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......ZZZZZZZZZZZZZZZZZZZ..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "............................",
    "........kkLbbbbbbbbbbbbLkkek",
    "........ZZZZZZZZZZZZZZZZZZZZ",
    "........kkLLLLLLLLLLLLLLkk..",
    "............................",
    ".......kkkkkGGGGGGGGGGGkkkkk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    "............................",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    "......kkkkkkHHHHHHHHHHHkk...",
    "............................",
    "......kmmmkppppk..kppppkk...",
    "......ZZZZZZZZZZZZZZZZZZZ...",
    ".........kkpplpk..kplppkk...",
    "............................",
    ".........kkkkkkk..kkkkkkk...",
    ".........ZZZZZZZZZZZZZZZZ...",
    "..........kaaak....kaaak....",
    "............................",
    "...........kak......kak.....",
    "............ZZZZZZZZZZ......",
  ],
  [
    ".................V..........",
    "................ZVZ.........",
    ".................V..........",
    ".................V..........",
    "................ZVZ.........",
    ".................V..........",
    ".................V..........",
    "..............ZZZVZZZ.......",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
    ".................V..........",
    ".................V..........",
  ],
  [
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "..............ZZZVZZZ.......",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
  ],
  [
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    "................ZVZ.........",
  ],
  [
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    ".................Z..........",
    ".................V..........",
  ],
];

// Beam-in-fly: the teleport, a one-shot of six frames at 70 ms (420 ms). Same canvas
// (28x37) and body position as `fly` frame 0; the bottom row is painted in every
// frame. beam-out: three scan lines of his colour across the body, the body
// sliced into bands, bars narrowing round a one-cell core, a three-cell column
// of light, the core alone, two cells on the ground; then nothing (the design
// removes him). beam-in is the same in reverse and its last frame IS `fly` frame 0, so
// the design cuts to that rest with no change. Quiet on purpose: no glow wider
// than seven cells, the only light colour is the one-cell core.
// The hovering arrival: cut to `fly` after its last frame, which is `fly` f0.
const luibotBeamInFly = [
  [
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    ".................Z..........",
    ".................V..........",
  ],
  [
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    "............................",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    ".................V..........",
    "................ZVZ.........",
  ],
  [
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "..............ZZZVZZZ.......",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
    "................ZVZ.........",
  ],
  [
    ".................V..........",
    "................ZVZ.........",
    ".................V..........",
    ".................V..........",
    "................ZVZ.........",
    ".................V..........",
    ".................V..........",
    "..............ZZZVZZZ.......",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "...........ZZZZZZVZZZZZZ....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    "............ZZZZZVZZZZZ.....",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
    ".................V..........",
    ".................V..........",
    ".............ZZZZVZZZZ......",
    ".................V..........",
    ".................V..........",
  ],
  [
    ".................ZZZZ.......",
    ".................kwwk.......",
    "............................",
    "..................kk........",
    "..................ZZZZZ.....",
    "..............kkkkkkkkk.....",
    "............................",
    "...........kkyyyyyyynkk.....",
    "...........ZZZZZZZZZZZZ.....",
    "...........kknnnnnnnykkkkkkk",
    "............................",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......ZZZZZZZZZZZZZZZZZZZ..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "............................",
    "........kkLbbbbbbbbbbbbLkkek",
    "........ZZZZZZZZZZZZZZZZZZZZ",
    "........kkLLLLLLLLLLLLLLkk..",
    "............................",
    ".......kkkkkGGGGGGGGGGGkkkkk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    "............................",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......ZZZZZZZZZZZZZZZZZZZZZ",
    "......kkkkkkHHHHHHHHHHHkk...",
    "............................",
    "......kmmmkppppk..kppppkk...",
    "......ZZZZZZZZZZZZZZZZZZZ...",
    ".........kkpplpk..kplppkk...",
    "............................",
    ".........kkkkkkk..kkkkkkk...",
    ".........ZZZZZZZZZZZZZZZZ...",
    "..........kaaak....kaaak....",
    "............................",
    "...........kak......kak.....",
    "............ZZZZZZZZZZ......",
  ],
  [
    ".................kkkk.......",
    ".................kwwk.......",
    ".................kkkk.......",
    "..................kk........",
    "..................kkkkk.....",
    "..............kkkkkkkkk.....",
    "...........kkkkyyyyyykk.....",
    "...........kkyyyyyyynkk.....",
    "...........kkynnnnnnnkk.....",
    "...........kknnnnnnnykkkkkkk",
    "...........kknyyyyyyyyyzyykk",
    ".......kkkkkkyyyyyyyzzzzkkkk",
    ".......kyzyyyyzzzzzzLLLLkk..",
    ".......kkkzzzzbbbbbbwwbLkkkk",
    "........kkLbwwbbbbbbwwbLkkek",
    "........kkLbbbbbbbbbbbbLkkek",
    "........kkLbbbbbwwbbbbbLkkkk",
    "........kkLLLLLLLLLLLLLLkk..",
    "........kkkkkkkkkkkkkkkkkk..",
    ".......kkkkkGGGGGGGGGGGkkkkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHDHDHHHHkHHkk",
    ".......kkHHkHHHHHHHHHHHkHHkk",
    ".......kkHHkHkkkkkkkkkHkHHkk",
    ".......kkHHkHHHHHHHHHHHkkkkk",
    "......kkkkkkHHHHHHHHHHHkk...",
    "......kmmmkkkkkkkkkkkkkkk...",
    "......kmmmkppppk..kppppkk...",
    "......kkkkkppppk..kppppkk...",
    ".........kkpplpk..kplppkk...",
    ".........keeeeek..keeeeek...",
    ".........kkkkkkk..kkkkkkk...",
    ".........kaaaaak..kaaaaak...",
    "..........kaaak....kaaak....",
    "..........kaaak....kaaak....",
    "...........kak......kak.....",
    "............k........k......",
  ],
];

export default {
  palette,
  actions: {
    idle: { durations: [2800, 160], frames: [open, blink] },
    wave: { interval: 220, frames: wave },
    fly: { interval: 260, frames: luibotFly },
    "fly-wave": { interval: 260, frames: luibotFlyWave },
    feed: { interval: 260, frames: luibotFeed },
    "fly-carry": { interval: 260, frames: luibotFlyCarry },
    "beam-out": { durations: [70, 70, 70, 70, 70, 70], frames: luibotBeamOut },
    "beam-in": { durations: [70, 70, 70, 70, 70, 70], frames: luibotBeamIn },
    "beam-out-fly": { durations: [70, 70, 70, 70, 70, 70], frames: luibotBeamOutFly },
    "beam-in-fly": { durations: [70, 70, 70, 70, 70, 70], frames: luibotBeamInFly },
  },
};
