// luibuilder: a boxy robot in Justin's day layer and his straw hat. 30x34,
// drawn 1 sprite px = 1 page px: an orange head with a darker visor, lit eyes
// and a mouth slit, one ear bolt; his rust over-shirt with the windowpane check
// worn open like a work jacket over the orange chest, sleeves ending in a cuff
// line with metal forearms and mittens below; wide grey pants and work boots.
// His attitude is the pose: the right hand rests on a stone block standing on
// the ground beside his right boot (block cols 24-29, its bottom ink on row 33
// with the boots), the left arm hangs. No pencil: the block alone says builder
// at true size, and a pencil small enough to fit read as a yellow flag. The
// body sits at the right edge; the six spare columns on the left are for the
// raised arm. Rows 0-1 are empty at rest so the hat can lift. Clothes and hat
// are Justin's exact colours so the three read as one family; orange, so it
// splits from luibot's blue on the axis Justin can see. Same row-of-characters
// format and outline rule as justin.js: 2px ink around the silhouette, 1px
// interior lines, 1px on the brim's top edge and around the small parts that
// would vanish under 2px (bolt, forearms and hands, block), which have their
// own letters.

const ink = "#1e1711"; // near-black warm brown, same as justin.js; never pure black
const shell = "#d1913f"; // orange metal: head and chest
const panel = "#a86f2c"; // darker orange: visor
const light = "#efe3cf";
const straw = "#d9b25a"; // Justin's hat
const strawShade = "#b8903f";
const hatBand = "#6e3b2e";
const block = "#b9b2a6"; // stone grey, light against the page and apart from the pants
const overshirt = "#a8674a"; // Justin's rust over-shirt
const overshirtCheck = "#8f5439"; // its windowpane check
const pants = "#6a6259"; // warm grey wool
const pantsCrease = "#7d756b";
const boots = "#54423a"; // Justin's shoes

const spark = "#b8903f"; // a spark off the hammer, loose in the air with no outline: straw shade, 2.4:1 on latte and 6:1 on the dark page (justin.js strawShade)

const beam = "#d1913f"; // the teleport beam: his shell orange, loose cells with no outline (6.6:1 on the dark page)
const beamCore = "#efe3cf"; // the beam's bright core, one cell wide, loose

const palette = {
  ".": null,
  k: ink,
  A: shell,
  a: shell, // bolt, forearms and hands
  D: panel,
  w: light,
  y: straw,
  z: strawShade,
  n: hatBand,
  B: block,
  O: overshirt,
  P: overshirtCheck,
  p: pants,
  l: pantsCrease,
  f: boots,
  s: spark,
  Z: beam,
  V: beamCore,
};

// Standing, hand on the block; the boots and the block never leave row 33.
// The blink darkens the eyes (rows 12-13) for one short frame every few
// seconds; nothing else moves.
const open = [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "...........kkyyyyyyyykk.......",
    "...........kknnnnnnnnkk.......",
    "...........kknnnnnnnnkk.......",
    "......kkkkkkkyyyyyyyykkkkkkk..",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......kkkkzzzzzzzzzzzzzzkkkk..",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkAAAAkkkkAAAAkk.....",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkkkkkkkkkkkkkkk.....",
    "......kkkkkOOOAAAAAAOOOkkkkk..",
    "......kkOOkPPPAAAAAAPPPkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkkkkPPPAAAAAAPPPkkkkk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kkaakOPOAAAAAAOPOkaakkkk",
    "......kaaakOPOAAAAAAOPOkkaaaak",
    "......kaaakpppppppppppkkkaaaak",
    "......kkkkkpppkkkkppppk.kkkkkk",
    "........kkpplpk..kplppk.kBBBBk",
    "........kkppppk..kppppk.kBBBBk",
    "........kkppppk..kppppk.kBBBBk",
    "........kkffffk..kffffk.kBBBBk",
    "........kkffffk..kffffk.kBBBBk",
    "........kkkkkkk..kkkkkk.kkkkkk",
];
const blink = open.map((row, y) => (y === 12 || y === 13 ? row.replace(/w/g, "D") : row));

// The greeting is a hat tip, not a wave (the straight brim sits exactly where a
// waving hand would go), drawn like Justin's own `hat` pose: the left sleeve
// stands up from the shoulder, cuff line at row 18, the metal forearm runs
// straight up beside the head (one clear column from it), and the mitten sits
// on the brim's left tip with the tip's two columns inside it and its own
// outline over the straw. Frame 0 is the grip with the hat level; frame 1 lifts
// the hat's left third one row (crown top steps, straw under the step), the
// hand rising with it, and is held for as long as the hover lasts (a long last
// duration; the design switches back to idle, which puts the hat down). The
// right hand stays on the block and the body does not move.
const tip = [
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "....kkkk...kkyyyyyyyykk.......",
    "...kkaakk..kknnnnnnnnkk.......",
    "...kaaaak..kknnnnnnnnkk.......",
    "...kaaaakkkkkyyyyyyyykkkkkkk..",
    "...kaaaakyzyyyyyyzyyyyyzyykk..",
    "...kkkkkkkzzzzzzzzzzzzzzkkkk..",
    "...kaaak.kkAAAAAAAAAAAAkk.....",
    "...kaaak.kkADDDDDDDDDDAkkkk...",
    "...kaaak.kkADwwDDDDwwDAkkak...",
    "...kaaak.kkADwwDDDDwwDAkkak...",
    "...kaaak.kkADDDDDDDDDDAkkkk...",
    "...kaaak.kkAAAAkkkkAAAAkk.....",
    "...kaaak.kkAAAAAAAAAAAAkk.....",
    "...kaaak.kkkkkkkkkkkkkkkk.....",
    "...kkkkkkkkOOOAAAAAAOOOkkkkk..",
    "....kOOOkkkPPPAAAAAAPPPkOOkk..",
    "....kOOOkkkOPOAAAAAAOPOkOOkk..",
    "....kOOOkkkOPOAAAAAAOPOkOOkk..",
    "....kkkkkkkPPPAAAAAAPPPkkkkk..",
    ".........kkOPOAAAAAAOPOkaakk..",
    ".........kkOPOAAAAAAOPOkaakkkk",
    ".........kkOPOAAAAAAOPOkkaaaak",
    "........kkppppppppppppkkkaaaak",
    "........kkppppkkkkppppk.kkkkkk",
    "........kkpplpk..kplppk.kBBBBk",
    "........kkppppk..kppppk.kBBBBk",
    "........kkppppk..kppppk.kBBBBk",
    "........kkffffk..kffffk.kBBBBk",
    "........kkffffk..kffffk.kBBBBk",
    "........kkkkkkk..kkkkkk.kkkkkk",
  ],
  [
    "..............................",
    "............kkk...............",
    "...........kkykkkkkkkk........",
    "....kkkk...kkyyyyyyyykk.......",
    "...kkaakk..kknyyyyyyykk.......",
    "...kaaaak..kknnnnnnnnkk.......",
    "...kaaaakkkkkynnnnnnnkk.......",
    "...kaaaakyyyyyyyyyyyykkkkkkk..",
    "...kkkkkkkzzzzyyyyyyyyyyyykk..",
    "...kaaak.kkkkkzzzzzzzzzzkkkk..",
    "...kaaak.kkAAAAAAAAAAAAkk.....",
    "...kaaak.kkADDDDDDDDDDAkkkk...",
    "...kaaak.kkADwwDDDDwwDAkkak...",
    "...kaaak.kkADwwDDDDwwDAkkak...",
    "...kaaak.kkADDDDDDDDDDAkkkk...",
    "...kaaak.kkAAAAkkkkAAAAkk.....",
    "...kaaak.kkAAAAAAAAAAAAkk.....",
    "...kaaak.kkkkkkkkkkkkkkkk.....",
    "...kkkkkkkkOOOAAAAAAOOOkkkkk..",
    "....kOOOkkkPPPAAAAAAPPPkOOkk..",
    "....kOOOkkkOPOAAAAAAOPOkOOkk..",
    "....kOOOkkkOPOAAAAAAOPOkOOkk..",
    "....kkkkkkkPPPAAAAAAPPPkkkkk..",
    ".........kkOPOAAAAAAOPOkaakk..",
    ".........kkOPOAAAAAAOPOkaakkkk",
    ".........kkOPOAAAAAAOPOkkaaaak",
    "........kkppppppppppppkkkaaaak",
    "........kkppppkkkkppppk.kkkkkk",
    "........kkpplpk..kplppk.kBBBBk",
    "........kkppppk..kppppk.kBBBBk",
    "........kkppppk..kppppk.kBBBBk",
    "........kkffffk..kffffk.kBBBBk",
    "........kkffffk..kffffk.kBBBBk",
    "........kkkkkkk..kkkkkk.kkkkkk",
  ],
];

// Stand: his rest without the stone block, for the projects pane where he builds
// and hops: idle's body and left arm, the right arm hanging like the left (the
// cells `build` uses), idle's blink. Same 30x34 canvas and body position. Rule:
// in a scene where he builds or hops, his rest is `stand`, never `idle`; `idle`
// and `wave` (with the block) are for the agents pane, where he never builds.
// The block would otherwise pop in and out on every cut.
const luibuilderStand = [
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "...........kkyyyyyyyykk.......",
    "...........kknnnnnnnnkk.......",
    "...........kknnnnnnnnkk.......",
    "......kkkkkkkyyyyyyyykkkkkkk..",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......kkkkzzzzzzzzzzzzzzkkkk..",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkAAAAkkkkAAAAkk.....",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkkkkkkkkkkkkkkk.....",
    "......kkkkkOOOAAAAAAOOOkkkkk..",
    "......kkOOkPPPAAAAAAPPPkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkkkkPPPAAAAAAPPPkkkkk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kaaakOPOAAAAAAOPOkaaak..",
    "......kaaakpppppppppppkkaaak..",
    "......kkkkkpppkkkkppppkkkkkk..",
    "........kkpplpk..kplppk.......",
    "........kkppppk..kppppk.......",
    "........kkppppk..kppppk.......",
    "........kkffffk..kffffk.......",
    "........kkffffk..kffffk.......",
    "........kkkkkkk..kkkkkk.......",
  ],
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "...........kkyyyyyyyykk.......",
    "...........kknnnnnnnnkk.......",
    "...........kknnnnnnnnkk.......",
    "......kkkkkkkyyyyyyyykkkkkkk..",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......kkkkzzzzzzzzzzzzzzkkkk..",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkADDDDDDDDDDAkkak...",
    ".........kkADDDDDDDDDDAkkak...",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkAAAAkkkkAAAAkk.....",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkkkkkkkkkkkkkkk.....",
    "......kkkkkOOOAAAAAAOOOkkkkk..",
    "......kkOOkPPPAAAAAAPPPkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkkkkPPPAAAAAAPPPkkkkk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kaaakOPOAAAAAAOPOkaaak..",
    "......kaaakpppppppppppkkaaak..",
    "......kkkkkpppkkkkppppkkkkkk..",
    "........kkpplpk..kplppk.......",
    "........kkppppk..kppppk.......",
    "........kkppppk..kppppk.......",
    "........kkffffk..kffffk.......",
    "........kkffffk..kffffk.......",
    "........kkkkkkk..kkkkkk.......",
  ],
];

// Build: a one-shot for a design to repeat a few times. Same 30x34 canvas and
// body as `idle` but without the stone block, the right arm hanging like the
// left. The left fist holds a small stone-grey hammer: raise (head up beside
// the brim), strike (arm down, the head hitting at the canvas's left edge: its
// ink face is x0-1, rows 19-25, the head x2-3 on two cells of handle), spark
// (the strike plus three straw specks a cell off the head). Put the thing he
// works on just left of the canvas, its edge at x-1, so the head lands on it at
// rows 20-24 (about his chest). His rest in a scene where he builds or hops is
// `stand`, never `idle`: the stone block must not pop in and out.
const luibuilderBuild = [
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "...........kkyyyyyyyykk.......",
    "...........kknnnnnnnnkk.......",
    "...........kknnnnnnnnkk.......",
    "......kkkkkkkyyyyyyyykkkkkkk..",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......kkkkzzzzzzzzzzzzzzkkkk..",
    ".........kkAAAAAAAAAAAAkk.....",
    "..kkkkk..kkADDDDDDDDDDAkkkk...",
    ".kkkkkkk.kkADwwDDDDwwDAkkak...",
    ".kkBBBkk.kkADwwDDDDwwDAkkak...",
    ".kkBBBkk.kkADDDDDDDDDDAkkkk...",
    "..kkBkk..kkAAAAkkkkAAAAkk.....",
    "..kkBkkkkkkAAAAAAAAAAAAkk.....",
    ".kkaaakkkkkkkkkkkkkkkkkkk.....",
    ".kaaaakOOOOOOOAAAAAAOOOkkkkk..",
    ".kaaaakOOOkPPPAAAAAAPPPkOOkk..",
    ".kaaaakOOOkOPOAAAAAAOPOkOOkk..",
    ".kkkkkkkkkkOPOAAAAAAOPOkOOkk..",
    "......kkkkkPPPAAAAAAPPPkkkkk..",
    ".........kkOPOAAAAAAOPOkaakk..",
    ".........kkOPOAAAAAAOPOkaakk..",
    ".........kkOPOAAAAAAOPOkaaak..",
    ".........kkpppppppppppkkaaak..",
    ".........kkpppkkkkppppkkkkkk..",
    "........kkpplpk..kplppk.......",
    "........kkppppk..kppppk.......",
    "........kkppppk..kppppk.......",
    "........kkffffk..kffffk.......",
    "........kkffffk..kffffk.......",
    "........kkkkkkk..kkkkkk.......",
  ],
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "...........kkyyyyyyyykk.......",
    "...........kknnnnnnnnkk.......",
    "...........kknnnnnnnnkk.......",
    "......kkkkkkkyyyyyyyykkkkkkk..",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......kkkkzzzzzzzzzzzzzzkkkk..",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkAAAAkkkkAAAAkk.....",
    "......kkkkkAAAAAAAAAAAAkk.....",
    ".....kkkkkkkkkkkkkkkkkkkk.....",
    "....kkOOOOOOOOAAAAAAOOOkkkkk..",
    "kkkkkOOOOkkPPPAAAAAAPPPkOOkk..",
    "kkkkkkkkkkkOPOAAAAAAOPOkOOkk..",
    "kkBBkkaaakkOPOAAAAAAOPOkOOkk..",
    "kkBBBBaaakkPPPAAAAAAPPPkkkkk..",
    "kkBBkkaaakkOPOAAAAAAOPOkaakk..",
    "kkkkkkkkkkkOPOAAAAAAOPOkaakk..",
    "kkkkkk..kkkOPOAAAAAAOPOkaaak..",
    ".........kkpppppppppppkkaaak..",
    ".........kkpppkkkkppppkkkkkk..",
    "........kkpplpk..kplppk.......",
    "........kkppppk..kppppk.......",
    "........kkppppk..kppppk.......",
    "........kkffffk..kffffk.......",
    "........kkffffk..kffffk.......",
    "........kkkkkkk..kkkkkk.......",
  ],
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "...........kkyyyyyyyykk.......",
    "...........kknnnnnnnnkk.......",
    "...........kknnnnnnnnkk.......",
    "......kkkkkkkyyyyyyyykkkkkkk..",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......kkkkzzzzzzzzzzzzzzkkkk..",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkAAAAkkkkAAAAkk.....",
    "......kkkkkAAAAAAAAAAAAkk.....",
    "s..s.kkkkkkkkkkkkkkkkkkkk.....",
    "....kkOOOOOOOOAAAAAAOOOkkkkk..",
    "kkkkkOOOOkkPPPAAAAAAPPPkOOkk..",
    "kkkkkkkkkkkOPOAAAAAAOPOkOOkk..",
    "kkBBkkaaakkOPOAAAAAAOPOkOOkk..",
    "kkBBBBaaakkPPPAAAAAAPPPkkkkk..",
    "kkBBkkaaakkOPOAAAAAAOPOkaakk..",
    "kkkkkkkkkkkOPOAAAAAAOPOkaakk..",
    "kkkkkk..kkkOPOAAAAAAOPOkaaak..",
    ".........kkpppppppppppkkaaak..",
    "s........kkpppkkkkppppkkkkkk..",
    "........kkpplpk..kplppk.......",
    "........kkppppk..kppppk.......",
    "........kkppppk..kppppk.......",
    "........kkffffk..kffffk.......",
    "........kkffffk..kffffk.......",
    "........kkkkkkk..kkkkkk.......",
  ],
];

// Hop: crouch, airborne, land. Canvas 34x34 (four spare columns on the right
// for the flung right arm), body at idle's x6-29, boots on row 33 in every
// frame, no stone block. Crouch: the body two rows lower on one row of leg.
// Airborne: three rows lower, boots tucked straight under the hips, both arms
// flung out; the design moves this frame along the arc. Land: the crouch with
// the arms still out. A design then returns to `idle` (with the block) or
// `build` (without).
const luibuilderHop = [
  [
    "..................................",
    "..................................",
    "..................................",
    "..................................",
    "............kkkkkkkkkk............",
    "...........kkyyyyyyyykk...........",
    "...........kkyyyyyyyykk...........",
    "...........kknnnnnnnnkk...........",
    "...........kknnnnnnnnkk...........",
    "......kkkkkkkyyyyyyyykkkkkkk......",
    "......kkyyzyyyyyyzyyyyyzyykk......",
    "......kkkkzzzzzzzzzzzzzzkkkk......",
    ".........kkAAAAAAAAAAAAkk.........",
    ".........kkADDDDDDDDDDAkkkk.......",
    ".........kkADwwDDDDwwDAkkak.......",
    ".........kkADwwDDDDwwDAkkak.......",
    ".........kkADDDDDDDDDDAkkkk.......",
    ".........kkAAAAkkkkAAAAkk.........",
    ".........kkAAAAAAAAAAAAkk.........",
    ".........kkkkkkkkkkkkkkkk.........",
    "......kkkkkOOOAAAAAAOOOkkkkk......",
    "......kkOOkPPPAAAAAAPPPkOOkk......",
    "......kkOOkOPOAAAAAAOPOkOOkk......",
    "......kkOOkOPOAAAAAAOPOkOOkk......",
    "......kkkkkPPPAAAAAAPPPkkkkk......",
    "......kkaakOPOAAAAAAOPOkaakk......",
    "......kkaakOPOAAAAAAOPOkaakk......",
    "......kaaakOPOAAAAAAOPOkaaak......",
    "......kaaakpppppppppppkkaaak......",
    "......kkkkkpppkkkkppppkkkkkk......",
    "........kkpplpk..kplppk...........",
    "........kkffffk..kffffk...........",
    "........kkffffk..kffffk...........",
    "........kkkkkkk..kkkkkk...........",
  ],
  [
    "..................................",
    "..................................",
    "..................................",
    "..................................",
    "..................................",
    "............kkkkkkkkkk............",
    "...........kkyyyyyyyykk...........",
    "...........kkyyyyyyyykk...........",
    "...........kknnnnnnnnkk...........",
    "...........kknnnnnnnnkk...........",
    "......kkkkkkkyyyyyyyykkkkkkk......",
    "......kkyyzyyyyyyzyyyyyzyykk......",
    "......kkkkzzzzzzzzzzzzzzkkkk......",
    ".........kkAAAAAAAAAAAAkk.........",
    ".........kkADDDDDDDDDDAkkkk.......",
    ".........kkADwwDDDDwwDAkkak.......",
    ".........kkADwwDDDDwwDAkkak.......",
    ".........kkADDDDDDDDDDAkkkk.......",
    ".........kkAAAAkkkkAAAAkk.........",
    "....kkkkkkkAAAAAAAAAAAAkkkkkkk....",
    "....kkkkkkkkkkkkkkkkkkkkkkkkkk....",
    "...kkOOOOOOOOOAAAAAAOOOOOOOOOkk...",
    "..kkOOOkkkkPPPAAAAAAPPPkkkkOOOkk..",
    ".kkOOOkkkkkOPOAAAAAAOPOkkkkkOOOkk.",
    ".kkkkkkk.kkOPOAAAAAAOPOkk.kkkkkkk.",
    "kkaaakk..kkPPPAAAAAAPPPkk..kkaaakk",
    "kkaaak...kkOPOAAAAAAOPOkk...kaaakk",
    "kkaaak...kkOPOAAAAAAOPOkk...kaaakk",
    "kkkkkk...kkOPOAAAAAAOPOkk...kkkkkk",
    ".........kkpppppppppppkkk.........",
    ".........kkpppkkkkppppkkk.........",
    "........kkffffk..kffffk...........",
    "........kkffffk..kffffk...........",
    "........kkkkkkk..kkkkkk...........",
  ],
  [
    "..................................",
    "..................................",
    "..................................",
    "..................................",
    "............kkkkkkkkkk............",
    "...........kkyyyyyyyykk...........",
    "...........kkyyyyyyyykk...........",
    "...........kknnnnnnnnkk...........",
    "...........kknnnnnnnnkk...........",
    "......kkkkkkkyyyyyyyykkkkkkk......",
    "......kkyyzyyyyyyzyyyyyzyykk......",
    "......kkkkzzzzzzzzzzzzzzkkkk......",
    ".........kkAAAAAAAAAAAAkk.........",
    ".........kkADDDDDDDDDDAkkkk.......",
    ".........kkADwwDDDDwwDAkkak.......",
    ".........kkADwwDDDDwwDAkkak.......",
    ".........kkADDDDDDDDDDAkkkk.......",
    ".........kkAAAAkkkkAAAAkk.........",
    "....kkkkkkkAAAAAAAAAAAAkkkkkkk....",
    "....kkkkkkkkkkkkkkkkkkkkkkkkkk....",
    "...kkOOOOOOOOOAAAAAAOOOOOOOOOkk...",
    "..kkOOOkkkkPPPAAAAAAPPPkkkkOOOkk..",
    ".kkOOOkkkkkOPOAAAAAAOPOkkkkkOOOkk.",
    ".kkkkkkk.kkOPOAAAAAAOPOkk.kkkkkkk.",
    "kkaaakk..kkPPPAAAAAAPPPkk..kkaaakk",
    "kkaaak...kkOPOAAAAAAOPOkk...kaaakk",
    "kkaaak...kkOPOAAAAAAOPOkk...kaaakk",
    "kkkkkk...kkOPOAAAAAAOPOkk...kkkkkk",
    ".........kkpppppppppppkkk.........",
    ".........kkpppkkkkppppkkk.........",
    "........kkpplpk..kplppk...........",
    "........kkffffk..kffffk...........",
    "........kkffffk..kffffk...........",
    "........kkkkkkk..kkkkkk...........",
  ],
];

// Beam-out: the teleport, a one-shot of six frames at 70 ms (420 ms). Same canvas
// (30x34) and body position as `stand` frame 0; the bottom row is painted in every
// frame. beam-out: three scan lines of his colour across the body, the body
// sliced into bands, bars narrowing round a one-cell core, a three-cell column
// of light, the core alone, two cells on the ground; then nothing (the design
// removes him). beam-in is the same in reverse and its last frame IS `stand` frame 0, so
// the design cuts to that rest with no change. Quiet on purpose: no glow wider
// than seven cells, the only light colour is the one-cell core.
// He teleports from and to `stand` (no block): the projects pane's rest. If he
// must leave the agents pane (where he rests in `idle` with the block), the
// design fades or slides the block on its own; a beam never carries it.
const luibuilderBeamOut = [
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "...........kkyyyyyyyykk.......",
    "...........kknnnnnnnnkk.......",
    "...........kknnnnnnnnkk.......",
    "......kkkkkkkyyyyyyyykkkkkkk..",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......kkkkzzzzzzzzzzzzzzkkkk..",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........ZZZZZZZZZZZZZZZZZZ...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkAAAAkkkkAAAAkk.....",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkkkkkkkkkkkkkkk.....",
    "......ZZZZZZZZZZZZZZZZZZZZZZ..",
    "......kkOOkPPPAAAAAAPPPkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkkkkPPPAAAAAAPPPkkkkk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kaaakOPOAAAAAAOPOkaaak..",
    "......ZZZZZZZZZZZZZZZZZZZZZZ..",
    "......kkkkkpppkkkkppppkkkkkk..",
    "........kkpplpk..kplppk.......",
    "........kkppppk..kppppk.......",
    "........kkppppk..kppppk.......",
    "........kkffffk..kffffk.......",
    "........kkffffk..kffffk.......",
    "........kkkkkkk..kkkkkk.......",
  ],
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "..............................",
    "...........kkyyyyyyyykk.......",
    "...........ZZZZZZZZZZZZ.......",
    "...........kknnnnnnnnkk.......",
    "..............................",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......ZZZZZZZZZZZZZZZZZZZZZZ..",
    ".........kkAAAAAAAAAAAAkk.....",
    "..............................",
    ".........kkADwwDDDDwwDAkkak...",
    ".........ZZZZZZZZZZZZZZZZZZ...",
    ".........kkADDDDDDDDDDAkkkk...",
    "..............................",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........ZZZZZZZZZZZZZZZZ.....",
    "......kkkkkOOOAAAAAAOOOkkkkk..",
    "..............................",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......ZZZZZZZZZZZZZZZZZZZZZZ..",
    "......kkkkkPPPAAAAAAPPPkkkkk..",
    "..............................",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......ZZZZZZZZZZZZZZZZZZZZZZ..",
    "......kaaakpppppppppppkkaaak..",
    "..............................",
    "........kkpplpk..kplppk.......",
    "........ZZZZZZZZZZZZZZZ.......",
    "........kkppppk..kppppk.......",
    "..............................",
    "........kkffffk..kffffk.......",
    "........ZZZZZZZZZZZZZZZ.......",
  ],
  [
    "..............................",
    "..............................",
    "................V.............",
    ".............ZZZVZZZ..........",
    "................V.............",
    "................V.............",
    ".............ZZZVZZZ..........",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "...........ZZZZZVZZZZZ........",
    "................V.............",
    "................V.............",
    "............ZZZZVZZZZ.........",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "............ZZZZVZZZZ.........",
    "................V.............",
    "................V.............",
    "............ZZZZVZZZZ.........",
  ],
  [
    "..............................",
    "..............................",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    ".............ZZZVZZZ..........",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
  ],
  [
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "...............ZVZ............",
  ],
  [
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "................Z.............",
    "................V.............",
  ],
];

// Beam-in: the teleport, a one-shot of six frames at 70 ms (420 ms). Same canvas
// (30x34) and body position as `stand` frame 0; the bottom row is painted in every
// frame. beam-out: three scan lines of his colour across the body, the body
// sliced into bands, bars narrowing round a one-cell core, a three-cell column
// of light, the core alone, two cells on the ground; then nothing (the design
// removes him). beam-in is the same in reverse and its last frame IS `stand` frame 0, so
// the design cuts to that rest with no change. Quiet on purpose: no glow wider
// than seven cells, the only light colour is the one-cell core.
const luibuilderBeamIn = [
  [
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "................Z.............",
    "................V.............",
  ],
  [
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "..............................",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "................V.............",
    "...............ZVZ............",
  ],
  [
    "..............................",
    "..............................",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    ".............ZZZVZZZ..........",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
    "...............ZVZ............",
  ],
  [
    "..............................",
    "..............................",
    "................V.............",
    ".............ZZZVZZZ..........",
    "................V.............",
    "................V.............",
    ".............ZZZVZZZ..........",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "...........ZZZZZVZZZZZ........",
    "................V.............",
    "................V.............",
    "............ZZZZVZZZZ.........",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "..........ZZZZZZVZZZZZZ.......",
    "................V.............",
    "................V.............",
    "............ZZZZVZZZZ.........",
    "................V.............",
    "................V.............",
    "............ZZZZVZZZZ.........",
  ],
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "..............................",
    "...........kkyyyyyyyykk.......",
    "...........ZZZZZZZZZZZZ.......",
    "...........kknnnnnnnnkk.......",
    "..............................",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......ZZZZZZZZZZZZZZZZZZZZZZ..",
    ".........kkAAAAAAAAAAAAkk.....",
    "..............................",
    ".........kkADwwDDDDwwDAkkak...",
    ".........ZZZZZZZZZZZZZZZZZZ...",
    ".........kkADDDDDDDDDDAkkkk...",
    "..............................",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........ZZZZZZZZZZZZZZZZ.....",
    "......kkkkkOOOAAAAAAOOOkkkkk..",
    "..............................",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......ZZZZZZZZZZZZZZZZZZZZZZ..",
    "......kkkkkPPPAAAAAAPPPkkkkk..",
    "..............................",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......ZZZZZZZZZZZZZZZZZZZZZZ..",
    "......kaaakpppppppppppkkaaak..",
    "..............................",
    "........kkpplpk..kplppk.......",
    "........ZZZZZZZZZZZZZZZ.......",
    "........kkppppk..kppppk.......",
    "..............................",
    "........kkffffk..kffffk.......",
    "........ZZZZZZZZZZZZZZZ.......",
  ],
  [
    "..............................",
    "..............................",
    "............kkkkkkkkkk........",
    "...........kkyyyyyyyykk.......",
    "...........kkyyyyyyyykk.......",
    "...........kknnnnnnnnkk.......",
    "...........kknnnnnnnnkk.......",
    "......kkkkkkkyyyyyyyykkkkkkk..",
    "......kkyyzyyyyyyzyyyyyzyykk..",
    "......kkkkzzzzzzzzzzzzzzkkkk..",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADwwDDDDwwDAkkak...",
    ".........kkADDDDDDDDDDAkkkk...",
    ".........kkAAAAkkkkAAAAkk.....",
    ".........kkAAAAAAAAAAAAkk.....",
    ".........kkkkkkkkkkkkkkkk.....",
    "......kkkkkOOOAAAAAAOOOkkkkk..",
    "......kkOOkPPPAAAAAAPPPkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkOOkOPOAAAAAAOPOkOOkk..",
    "......kkkkkPPPAAAAAAPPPkkkkk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kkaakOPOAAAAAAOPOkaakk..",
    "......kaaakOPOAAAAAAOPOkaaak..",
    "......kaaakpppppppppppkkaaak..",
    "......kkkkkpppkkkkppppkkkkkk..",
    "........kkpplpk..kplppk.......",
    "........kkppppk..kppppk.......",
    "........kkppppk..kppppk.......",
    "........kkffffk..kffffk.......",
    "........kkffffk..kffffk.......",
    "........kkkkkkk..kkkkkk.......",
  ],
];

export default {
  palette,
  actions: {
    idle: { durations: [3400, 160], frames: [open, blink] },
    wave: { durations: [240, 600000], frames: tip },
    stand: { durations: [3400, 160], frames: luibuilderStand },
    build: { durations: [300, 120, 180], frames: luibuilderBuild },
    hop: { durations: [140, 420, 140], frames: luibuilderHop },
    "beam-out": { durations: [70, 70, 70, 70, 70, 70], frames: luibuilderBeamOut },
    "beam-in": { durations: [70, 70, 70, 70, 70, 70], frames: luibuilderBeamIn },
  },
};
