// Truffle, dark brindle French bulldog, about 20px tall lying down. Everything
// that says "Frenchie" is in the head, one 20x15 template shared by every pose
// and always facing the viewer while the body is side-on, head to the right:
// bat ears drawn as round-topped paddles (a 3px tip over two rows of open
// inner ear inside a 1px rim, flaring at the base into the corners of a flat
// skull; five rows above the skull in every pose, and rigid: in the gaits the
// whole head bobs with the body as one block), a broad face with 2x2 dark eyes (glint top-left) set wide on the row
// above the nose, a shade line for the fold over a 4x2 nose, lips falling from
// the nose corners round a greying chin. Barrel body with a level back, a lit
// top row, a two-row shade band and a belly that sags between the legs; short
// thick legs; no tail.
//
// Same row-of-characters format as justin.js. Outline rule: closed 2px outer
// outline in ink on the body and head; 1px on the "thin" letters (e ear coat,
// n inner ear, a near legs and paws, d far legs, s shade). A 1px outline may
// step diagonally (corner pixels touch) as at the ear tips; the 2px outline
// never does. Interior lines and small features are 1px.
//
// `stride`: sprite px of ground travel per frame for a gait; a caller that
// moves her by distance should advance one frame per `stride` px so the
// planted feet do not skate. walk = 2 (a stroll), trot = 6.
//
// Generated from hand-drawn parts by scratchpad/truffle-fix1/build3.mjs; edit
// there and rebuild, or edit rows here and keep them the same length.

const ink = "#1e1711"; // near-black warm brown, same as justin.js; never pure black
// Provisional palette (Justin has not seen it): the coat sits ~2.6:1 off the
// ink so the shade band and lit row register at true size while she still
// reads as a dark dog; it is also a step off Justin's hair (#563f33).
const coat = "#6b5644"; // dark brindle base
const coatShade = "#4e3d33"; // underside, far-side legs, the fold over the nose
const coatLight = "#856d56"; // one row along the top of the back and skull
const brindle = "#8f6e4f"; // tan streaks, 3px dashes, sparse: a step lighter than the coat, not freckles
const muzzle = "#948a7e"; // greying chin between the jowls
const earInner = "#9a7570"; // the open inside of the bat ear, dusky pink
const eye = "#efe3cf"; // the one glint in each eye

const palette = {
  ".": null,
  k: ink,
  B: coat,
  e: coat, // ear coat: thin, 1px outline
  a: coat, // near legs and paws: thin
  d: coatShade, // far-side legs: thin
  s: coatShade, // underside shading and the nose fold: interior
  L: coatLight,
  t: brindle,
  g: muzzle,
  n: earInner,
  w: eye,
};

// Lying down, head on her front paws, eyes shut, ears up (Frenchie ears stay
// up asleep). Rows 0-1 are spare for the ear lift. Frame 2: the back rises one
// row; a long rest and a short rise (durations).
const sleep = [
  [
    "....................................",
    "....................................",
    ".................kkk............kkk.",
    "................knnnk..........knnnk",
    "................knnnk..........knnnk",
    "................knnnek........kennnk",
    "................kknneekk....kkeennkk",
    ".......kkkkkkkkkkkeeeekkkkkkkkeeeekk",
    ".....kkkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "...kkkkkLLLLLLLLkkBBBBBLLLLLLBBBBBkk",
    "..kkkkBBBBBBBBBBkkBBBBBBBBBBBBBBBBkk",
    ".kkkBBBBBBBBBBBBkkBBkkBBssssBBkkBBkk",
    "kkkBBtttBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBtttkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBBBBkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkBBssssssssssssskaaakaaakkaaakaaak.",
    "kkBsssssssssssssskaaakaaakkaaakaaak.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  ],
  [
    "....................................",
    "....................................",
    ".................kkk............kkk.",
    "................knnnk..........knnnk",
    "................knnnk..........knnnk",
    "................knnnek........kennnk",
    ".......kkkkkkkkkkknneekk....kkeennkk",
    ".....kkkkkkkkkkkkkeeeekkkkkkkkeeeekk",
    "....kkkkLLLLLLLLkkBBBBBkkkkkkBBBBBkk",
    "...kkkBBBBBBBBBBkkBBBBBLLLLLLBBBBBkk",
    "..kkkBBBBBBBBBBBkkBBBBBBBBBBBBBBBBkk",
    ".kkkBBBBBBBBBBBBkkBBkkBBssssBBkkBBkk",
    "kkkBBtttBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBtttkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBBBBkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkBBssssssssssssskaaakaaakkaaakaaak.",
    "kkBsssssssssssssskaaakaaakkaaakaaak.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  ],
];

// Checking who is there without getting up: the right ear pricks two rows
// higher and that eye opens a slit, the ear settles a row, then she is back
// asleep (the last frame is sleep frame 1, held) until the action restarts.
const ear = [
  [
    "................................kkk.",
    "...............................knnnk",
    ".................kkk...........knnnk",
    "................knnnk..........knnnk",
    "................knnnk..........knnnk",
    "................knnnek........kennnk",
    "................kknneekk....kkeennkk",
    ".......kkkkkkkkkkkeeeekkkkkkkkeeeekk",
    ".....kkkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "...kkkkkLLLLLLLLkkBBBBBLLLLLLBBBBBkk",
    "..kkkkBBBBBBBBBBkkBBBBBBBBBBBBBBBBkk",
    ".kkkBBBBBBBBBBBBkkBBkkBBssssBBwkBBkk",
    "kkkBBtttBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBtttkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBBBBkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkBBssssssssssssskaaakaaakkaaakaaak.",
    "kkBsssssssssssssskaaakaaakkaaakaaak.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  ],
  [
    "....................................",
    "................................kkk.",
    ".................kkk...........knnnk",
    "................knnnk..........knnnk",
    "................knnnk..........knnnk",
    "................knnnek........kennnk",
    "................kknneekk....kkeennkk",
    ".......kkkkkkkkkkkeeeekkkkkkkkeeeekk",
    ".....kkkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "...kkkkkLLLLLLLLkkBBBBBLLLLLLBBBBBkk",
    "..kkkkBBBBBBBBBBkkBBBBBBBBBBBBBBBBkk",
    ".kkkBBBBBBBBBBBBkkBBkkBBssssBBwkBBkk",
    "kkkBBtttBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBtttkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBBBBkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkBBssssssssssssskaaakaaakkaaakaaak.",
    "kkBsssssssssssssskaaakaaakkaaakaaak.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  ],
  [
    "....................................",
    "....................................",
    ".................kkk............kkk.",
    "................knnnk..........knnnk",
    "................knnnk..........knnnk",
    "................knnnek........kennnk",
    "................kknneekk....kkeennkk",
    ".......kkkkkkkkkkkeeeekkkkkkkkeeeekk",
    ".....kkkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "...kkkkkLLLLLLLLkkBBBBBLLLLLLBBBBBkk",
    "..kkkkBBBBBBBBBBkkBBBBBBBBBBBBBBBBkk",
    ".kkkBBBBBBBBBBBBkkBBkkBBssssBBkkBBkk",
    "kkkBBtttBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBtttkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBBBBBBkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkBBssssssssssssskaaakaaakkaaakaaak.",
    "kkBsssssssssssssskaaakaaakkaaakaaak.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
    "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
  ],
];

// Sitting up, awake, from the front: shoulders as wide as the head, wide-set
// thick front legs with the belly hanging low between them, haunches outside
// and the hind paws poking out beside the front ones.
const sit = [
  [
    "........................",
    "...kkk............kkk...",
    "..knnnk..........knnnk..",
    "..knnnk..........knnnk..",
    "..knnnek........kennnk..",
    "..kknneekk....kkeennkk..",
    "..kkeeeekkkkkkkkeeeekk..",
    "..kkBBBBBkkkkkkBBBBBkk..",
    "..kkBBBBBLLLLLLBBBBBkk..",
    "..kkBBBBBBBBBBBBBBBBkk..",
    "..kkBBwkBBssssBBwkBBkk..",
    "..kkBBkkBBkkkkBBkkBBkk..",
    "..kkBBBBBBkkkkBBBBBBkk..",
    "..kkBBBBkkggggkkBBBBkk..",
    "..kkkkkkkkkkkkkkkkkkkk..",
    ".kkkBBBBBBBBBBBBBBBBkkk.",
    "kkkBBBBBBBBBBBBBBBBBBkkk",
    "kkBBBBBBBBBBBBBBBBBBBBkk",
    "kkBBkaaaakBssBkaaaakBBkk",
    "kkBBkaaaakBssBkaaaakBBkk",
    "kkBBkaaaaksssskaaaakBBkk",
    "kaaakaaaakkkkkkaaaakaaak",
    "kaaakaaaak....kaaaakaaak",
    "kkkkkkkkkk....kkkkkkkkkk",
  ],
];

// Lateral-sequence walk: near hind lands F0, near front F2, far hind F4, far
// front F6, each a quarter cycle apart, so three then two feet are always
// down. Each foot spends five frames planted moving back 2px per frame and
// three swinging, its centre stepping 2, 3, 2, 1px. Far legs are directly
// behind the near ones and darker; mid-swing a far leg passes behind the
// planted near leg and is hidden for that frame, as it would be. The body and
// the whole head, ears included, drop one row together after each front-foot
// landing; nothing changes length.
const walk = [
  [
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "..kdddk...kkkkkkkkkkkkkkaaak......",
    "..kdddk...kaaak.......kkaaak......",
    "..kdddk...kaaak.......kkaaak......",
    "..kdddk...kaaak.......kkkkkk......",
    "..kdddk...kaaak.......kdddk.......",
    "..kkkkk...kkkkk.......kkkkk.......",
  ],
  [
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "....kdddkaaakkkkkkkkkkkkkkaaak....",
    "....kdddkaaak.......kdddkkaaak....",
    "....kdddkaaak.......kdddkkaaak....",
    "....kdddkaaak.......kdddkkaaak....",
    "....kkkkkaaak.......kdddkkkkkk....",
    "........kkkkk.......kkkkk.........",
  ],
  [
    "..................................",
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "......kaaakkkkkkkkkkkkkk..kaaak...",
    "......kaaakk......kdddk...kaaak...",
    "......kaaakk......kdddk...kaaak...",
    "......kaaak.......kdddk...kaaak...",
    "......kkkkk.......kkkkk...kkkkk...",
  ],
  [
    "..................................",
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "....kaaakkddkkkkkkkkkkkkkaaak.....",
    "....kaaakkdddk......kdddkaaak.....",
    "....kaaakkdddk......kdddkaaak.....",
    "....kaaakkkkkk......kkkkkaaak.....",
    "....kkkkk...............kkkkk.....",
  ],
  [
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "..kaaak...kkkkkkkkkkkkkkaakk......",
    "..kaaak...kdddk.......kaaakk......",
    "..kaaak...kdddk.......kaaakk......",
    "..kaaak...kdddk.......kaaakk......",
    "..kaaak...kdddk.......kaaak.......",
    "..kkkkk...kkkkk.......kkkkk.......",
  ],
  [
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "....kaaakdddkkkkkkkkkkkkkkdddk....",
    "....kaaakdddk.......kaaakkdddk....",
    "....kaaakdddk.......kaaakkdddk....",
    "....kaaakdddk.......kaaakkdddk....",
    "....kkkkkdddk.......kaaakkkkkk....",
    "........kkkkk.......kkkkk.........",
  ],
  [
    "..................................",
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "......kkaaakkkkkkkkkkkkk..kdddk...",
    "......kkaaak......kaaak...kdddk...",
    "......kkkkkk......kaaak...kdddk...",
    "......kdddk.......kaaak...kdddk...",
    "......kkkkk.......kkkkk...kkkkk...",
  ],
  [
    "..................................",
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "....kdddkkaakkkkkkkkkkkkkdddk.....",
    "....kdddkkaaak......kaaakdddk.....",
    "....kdddkkaaak......kaaakdddk.....",
    "....kdddkkkkkk......kkkkkdddk.....",
    "....kkkkk...............kkkkk.....",
  ],
];

// Trot: diagonal pairs (near hind + far front, then near front + far hind)
// land together, two feet down at a time, the near legs scissoring. Contact
// at +3, mid-stance at -3 (the planted foot moves 6px per frame: stride 6),
// then a high swing and a reaching swing. The body and head drop one row
// together on the mid-stance frames.
const trot = [
  [
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ".....kdddkaakkkkkkkkkkkkkkdddk....",
    ".....kdddkaaak.......kaaakdddk....",
    ".....kdddkaaak.......kaaakdddk....",
    ".....kkkkkaaak.......kkkkkdddk....",
    ".........kaaak...........kdddk....",
    ".........kkkkk...........kkkkk....",
  ],
  [
    "..................................",
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "...kaaakkdddkkkkkkkkkkkkkaaak.....",
    "...kaaakkdddk......kdddkkaaak.....",
    "...kaaakkdddk......kdddkkaaak.....",
    "...kaaakkkkkk......kdddkkkkkk.....",
    "...kkkkk...........kkkkk..........",
  ],
  [
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    ".....kaaakddkkkkkkkkkkkkkkaaak....",
    ".....kaaakdddk.......kdddkaaak....",
    ".....kaaakdddk.......kdddkaaak....",
    ".....kkkkkdddk.......kkkkkaaak....",
    ".........kdddk...........kaaak....",
    ".........kkkkk...........kkkkk....",
  ],
  [
    "..................................",
    "..................................",
    "..................................",
    "...............kkk............kkk.",
    "..............knnnk..........knnnk",
    "..............knnnk..........knnnk",
    "..............knnnek........kennnk",
    "..............kknneekk....kkeennkk",
    "..............kkeeeekkkkkkkkeeeekk",
    "....kkkkkkkkkkkkBBBBBkkkkkkBBBBBkk",
    "..kkkkkkkkkkkkkkBBBBBLLLLLLBBBBBkk",
    ".kkkkLLLLLLLLLkkBBBBBBBBBBBBBBBBkk",
    "kkkBBBBBBBBBBBkkBBwkBBssssBBwkBBkk",
    "kkBBBtttBBBBBBkkBBkkBBkkkkBBkkBBkk",
    "kkBBBBBBBBBBBBkkBBBBBBkkkkBBBBBBkk",
    "kkBBBBBBBBBtttkkBBBBkkggggkkBBBkkk",
    "kkBBtttBBBBBBBBkkkkkkkkkkkkkkkkkk.",
    "kkkBssssssssssssssssssssssssssBkk.",
    ".kkksssssssssssssssssssssssssBBkk.",
    "..kkkkkkkkkkkssssssssssskkkkkkkkk.",
    "...kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "...kdddkkaaakkkkkkkkkkkkkdddk.....",
    "...kdddkkaaak......kaaakkdddk.....",
    "...kdddkkaaak......kaaakkdddk.....",
    "...kdddkkkkkk......kaaakkkkkk.....",
    "...kkkkk...........kkkkk..........",
  ],
];

export default {
  palette,
  actions: {
    sleep: { interval: 1500, durations: [2300, 700], frames: sleep },
    ear: { interval: 700, durations: [1100, 300, 600000], frames: ear },
    sit: { frames: sit },
    walk: { interval: 110, stride: 2, frames: walk },
    trot: { interval: 90, stride: 6, frames: trot },
  },
};
